"""
strategies_loop.py — Batch loop configuration.
Edit param_grid, n_symbols and order_amount before each run.
This file is NOT updated by the batch automatically.
"""

STRATEGIES_LOOP = [
    {
        "id": "02_reversal_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [2,3,5,6],
            "TOLERANCE": [30,40,50],
            "MA_PERIOD": [10,25],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "03_parity_long_4H",
        "n_symbols": 20,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50,100,150],
            "TOLERANCE": [20,30,40],
            "MA_PERIOD": [10,25,50],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "04_reversal_short_4H",
        "n_symbols": 20,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [2,3,4],
            "TOLERANCE": [10,20,30],
            "MA_PERIOD": [10,25],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "06_reversal_long_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [100],
            "LOOKBACK": [6,7,8,9],
            "TOLERANCE": [10,20,25],
            "MA_PERIOD": [10,25],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "07_reversal_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [100],
            "LOOKBACK": [4,5,6],
            "TOLERANCE": [5,10,15],
            "MA_PERIOD": [10,25],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "08_reversal_long_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [2,3,4],
            "TOLERANCE": [5,10,15],
            "MA_PERIOD": [10,25],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "09_reversal_short_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [2,3,4],
            "TOLERANCE": [40,50,60],
            "MA_PERIOD": [10,25],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "10_parity_long_1H",
        "n_symbols": 20,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [75],
            "LOOKBACK": [50,100,150],
            "TOLERANCE": [4,6,8,10],
            "MA_PERIOD": [10,25],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "11_parity_short_1H",
        "n_symbols":10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [100],
            "LOOKBACK": [50,100],
            "TOLERANCE": [4,6,8,10],
            "MA_PERIOD": [10,25],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "12_parity_long_6Hutc",
        "n_symbols": 20,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50,100],
            "TOLERANCE": [10,20,30],
            "MA_PERIOD": [10,25],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "13_orderblocks_short_4H",
        "n_symbols": 30,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50,100,150],
            "TOLERANCE": [25,35,45],
            "IMPULSE": [0.02,0.05,0.08],
            "TP_PCT": [2,3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "17_flag_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [8,10,12],
            "MA_PERIOD": [10,25],
            "IMPULSE": [3,4,5],
            "FLAG": [10,20,30],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "18_flag_long_1H",
        "n_symbols": 20,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20,40,60],
            "MA_PERIOD": [10,25],
            "IMPULSE": [2,3,4],
            "FLAG": [10,20,30],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "19_flag_short_4H",
        "n_symbols": 20,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [8,10,12],
            "MA_PERIOD": [10,25],
            "IMPULSE": [1,2,3],
            "FLAG": [30,40,50],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "20_flag_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": { 
            "SELL_AFTER": [100],
            "LOOKBACK": [20,40,60],
            "MA_PERIOD": [10,25],
            "IMPULSE": [2,3,4],
            "FLAG": [10,20,30],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "21_parity_short_4H",
        "n_symbols": 20,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50,100,150],
            "TOLERANCE": [20,30,40],
            "MA_PERIOD": [10,25,50],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "22_parity_short_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50,100],
            "TOLERANCE": [10,20,30],
            "MA_PERIOD": [10,25],
            "TP_PCT": [2,3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "24_flag_long_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [40,50,60],
            "MA_PERIOD": [10,25],
            "IMPULSE": [1,2,3],
            "FLAG": [20,30,40],
            "TP_PCT": [3,4],
            "SL_PCT": [3],
        },
    },
    {
        "id": "25_flag_short_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [40,50,60],
            "MA_PERIOD": [10,25],
            "IMPULSE": [1,2,3],
            "FLAG": [20,30,40],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "26_orderblocks_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50,100,150],
            "TOLERANCE": [25,35,45],
            "IMPULSE": [0.02,0.05,0.08],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "27_orderblocks_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [75],
            "LOOKBACK": [30,50,75],
            "TOLERANCE": [25,35,45],
            "IMPULSE": [0.02,0.05,0.08],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
    {
        "id": "28_orderblocks_long_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [75],
            "LOOKBACK": [30,50,75],
            "TOLERANCE": [25,35,45],
            "IMPULSE": [0.02,0.05,0.08],
            "TP_PCT": [3,4],
            "SL_PCT": [2],
        },
    },
]