# Auto-generated by regime03_bin_search.py
# Source: symbol_strategy_tf | MA20 | ER>0.4 | ATR>2.0
# Train: IS

REGIME_SOURCE    = 'symbol_strategy_tf'
REGIME_MA_PERIOD = 20
REGIME_ER_TH     = 0.4
REGIME_ATR_TH    = 2.0

REGIME_BINS = {
    "01_reversal_long_15m": {"ranging_dwtrend", "ranging_uptrend", "volatile_dwtrend"},
    "02_reversal_short_15m": {"ranging_uptrend"},
    "03_reversal_long_30m": {"trending_uptrend"},
    "04_reversal_short_30m": {"ranging_uptrend", "volatile_dwtrend", "volatile_uptrend"},
    "05_reversal_long_1H": {},
    "06_reversal_short_1H": {"ranging_uptrend"},
    "07_reversal_long_4H": {"ranging_dwtrend"},
    "08_reversal_short_4H": {"ranging_uptrend", "trending_uptrend"},
    "09_reversal_long_6Hutc": {"ranging_dwtrend", "volatile_dwtrend"},
    "10_reversal_short_6Hutc": {"ranging_uptrend"},
    "11_parity_long_15m": {"ranging_dwtrend", "ranging_uptrend", "trending_dwtrend", "trending_uptrend"},
    "12_parity_short_15m": {},
    "13_parity_long_30m": {},
    "14_parity_short_30m": {"volatile_uptrend"},
    "15_parity_long_1H": {},
    "16_parity_short_1H": {"volatile_uptrend"},
    "17_parity_long_4H": {"ranging_dwtrend"},
    "18_parity_short_4H": {"ranging_uptrend", "trending_uptrend", "volatile_uptrend"},
    "19_parity_long_6Hutc": {"ranging_dwtrend", "ranging_uptrend", "trending_dwtrend", "volatile_dwtrend"},
    "20_parity_short_6Hutc": {"ranging_uptrend"},
    "21_flag_long_15m": {"ranging_dwtrend"},
    "22_flag_short_15m": {"ranging_uptrend"},
    "23_flag_long_30m": {"trending_uptrend"},
    "24_flag_short_30m": {"trending_uptrend", "volatile_dwtrend"},
    "25_flag_long_1H": {},
    "26_flag_short_1H": {"ranging_uptrend"},
    "27_flag_long_4H": {"ranging_dwtrend", "trending_uptrend"},
    "28_flag_short_4H": {"ranging_dwtrend", "ranging_uptrend", "trending_uptrend"},
    "29_flag_long_6Hutc": {},
    "30_flag_short_6Hutc": {},
    "31_orderblocks_long_15m": {"ranging_dwtrend", "volatile_uptrend"},
    "32_orderblocks_short_15m": {"ranging_uptrend"},
    "33_orderblocks_long_30m": {"ranging_dwtrend"},
    "34_orderblocks_short_30m": {"ranging_uptrend", "trending_uptrend", "volatile_uptrend"},
    "35_orderblocks_long_1H": {"ranging_uptrend", "volatile_dwtrend"},
    "36_orderblocks_short_1H": {"ranging_uptrend", "volatile_uptrend"},
    "37_orderblocks_long_4H": {"ranging_uptrend", "volatile_dwtrend", "volatile_uptrend"},
    "38_orderblocks_short_4H": {"volatile_uptrend"},
    "39_orderblocks_long_6Hutc": {"volatile_dwtrend", "volatile_uptrend"},
    "40_orderblocks_short_6Hutc": {},
}
