"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-07-16 11:42. Do not edit manually.

Train windows:
  12Hutc: 2025-10-08 → 2026-07-08  (9m train)  |  next train: 2026-09-08  (+2m)
"""

STRATEGIES = [
    {
        "id": "00011_12Hutc_short_ADX14gt20_AND_HISTVOL30ltSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "adx", "period": 14, "op": ">", "value": 20}, {"type": "histvol_regime", "period": 30, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 9,
        "sl_pct": 7,
    },
]
