"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-07-13 17:03. Do not edit manually.

Train windows:
  12Hutc: 2025-10-08 → 2026-07-08  (9m train)  |  next train: 2026-09-08  (+2m)
"""

STRATEGIES = [
    {
        "id": "00002_12Hutc_long_RSI7gt50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "rsi", "period": 7, "op": ">", "value": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 2,
    },
    {
        "id": "00035_12Hutc_long_CLOSEgtCLOSEm10",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "momentum", "op": ">", "value": 10}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 2,
        "sl_pct": 10,
    },
]
