"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-07-20 16:23. Do not edit manually.

Train windows:
  6Hutc : 2025-10-08 → 2026-07-08  (9m train)  |  next train: 2026-09-08  (+2m)
  12Hutc: 2025-10-08 → 2026-07-08  (9m train)  |  next train: 2026-09-08  (+2m)
"""

STRATEGIES = [
    {
        "id": "00046_6Hutc_long_RSI14lt70_AND_ADX14gt30",
        "timeframe": "6Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "rsi", "period": 14, "op": "<", "value": 70}, {"type": "adx", "period": 14, "op": ">", "value": 30}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 7,
        "sl_pct": 7,
    },
    {
        "id": "00515_12Hutc_short_RSI14gt30_AND_CLOSEltMA100_AND_ATR14gtSMA_ATR10",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 14, "op": ">", "value": 30}, {"type": "ma", "op": "<", "value": 100}, {"type": "atr_regime", "period": 14, "op": ">", "sma_period": 10}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 9,
        "sl_pct": 4,
    },
]
