"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-07-30 15:14. Do not edit manually.

Launch config:
  DSR_TH = 0.8
  WFO_NET_GAIN_TH = 30
  WFO_DD_TH = 15
  WFO_R2_TH = 0.8
  WFO_WFR_TH = 0.6
  CORRELATION_DD_TH = 0.55
  MONTECARLO_RUIN_TH = 10
  MULTIVERSE_PVALUE_TH = 0.05

Train windows:
  6Hutc : 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
  12Hutc: 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
  1H    : 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
  4H    : 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
"""

STRATEGIES = [
    {
        "id": "08382_1H_long_RSI7gt70_AND_ATR7gtSMA_ATR50_AND_HISTVOL30ltSMA_HISTVOL20",
        "timeframe": "1H",
        "active": True,
        "direction": "long",
        "specs": [{"type": "rsi", "period": 7, "op": ">", "value": 70}, {"type": "atr_regime", "period": 7, "op": ">", "sma_period": 50}, {"type": "histvol_regime", "period": 30, "op": "<", "sma_period": 20}],
        "sell_after_ncandles": 50,
        "order_amount": 500,
        "tp_pct": 10,
        "sl_pct": 6,
    },
    {
        "id": "26749_6Hutc_long_CLOSEgtMA20_AND_HISTVOL10gtSMA_HISTVOL20_AND_HISTVOL30gtSMA_HISTVOL20",
        "timeframe": "6Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "ma", "op": ">", "value": 20}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 20}, {"type": "histvol_regime", "period": 30, "op": ">", "sma_period": 20}],
        "sell_after_ncandles": 50,
        "order_amount": 500,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "29493_12Hutc_long_CLOSEltCLOSEm10_AND_HISTVOL10ltSMA_HISTVOL20_AND_HISTVOL10gtSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "momentum", "op": "<", "value": 10}, {"type": "histvol_regime", "period": 10, "op": "<", "sma_period": 20}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 500,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "29781_12Hutc_long_CLOSEltCLOSEm20_AND_ATR14ltSMA_ATR10_AND_HISTVOL10gtSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "momentum", "op": "<", "value": 20}, {"type": "atr_regime", "period": 14, "op": "<", "sma_period": 10}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 500,
        "tp_pct": 6,
        "sl_pct": 10,
    },
    {
        "id": "44789_12Hutc_short_RSI14lt50_AND_CLOSEgtCLOSEm20_AND_HISTVOL30ltSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 14, "op": "<", "value": 50}, {"type": "momentum", "op": ">", "value": 20}, {"type": "histvol_regime", "period": 30, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 500,
        "tp_pct": 8,
        "sl_pct": 10,
    },
    {
        "id": "53019_4H_short_ADX7gt25_AND_CLOSEltMA100_AND_HISTVOL30gtSMA_HISTVOL50",
        "timeframe": "4H",
        "active": True,
        "direction": "short",
        "specs": [{"type": "adx", "period": 7, "op": ">", "value": 25}, {"type": "ma", "op": "<", "value": 100}, {"type": "histvol_regime", "period": 30, "op": ">", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 500,
        "tp_pct": 6,
        "sl_pct": 6,
    },
    {
        "id": "54965_12Hutc_short_ADX14gt25_AND_CLOSEgtCLOSEm20_AND_HISTVOL30ltSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "adx", "period": 14, "op": ">", "value": 25}, {"type": "momentum", "op": ">", "value": 20}, {"type": "histvol_regime", "period": 30, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 500,
        "tp_pct": 8,
        "sl_pct": 8,
    },
    {
        "id": "60319_12Hutc_short_CLOSEltCLOSEm10_AND_HISTVOL10gtSMA_HISTVOL20_AND_HISTVOL10ltSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "momentum", "op": "<", "value": 10}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 20}, {"type": "histvol_regime", "period": 10, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 500,
        "tp_pct": 6,
        "sl_pct": 6,
    },
]
