"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-07-27 17:08. Do not edit manually.

Launch config:
  DSR_TH = 0.95
  WFO_NET_GAIN_TH = 40
  WFO_DD_TH = 15
  WFO_R2_TH = 0.8
  WFO_WFR_TH = 0.6
  CORRELATION_DD_TH = 0.55
  MONTECARLO_RUIN_TH = 10
  MULTIVERSE_PVALUE_TH = 0.05

Train windows:
  12Hutc: 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
  6Hutc : 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
"""

STRATEGIES = [
    {
        "id": "29493_12Hutc_long_CLOSEltCLOSEm10_AND_HISTVOL10ltSMA_HISTVOL20_AND_HISTVOL10gtSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "momentum", "op": "<", "value": 10}, {"type": "histvol_regime", "period": 10, "op": "<", "sma_period": 20}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "35236_6Hutc_short_RSI7lt30_AND_ATR14ltSMA_ATR50_AND_HISTVOL10gtSMA_HISTVOL20",
        "timeframe": "6Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 7, "op": "<", "value": 30}, {"type": "atr_regime", "period": 14, "op": "<", "sma_period": 50}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 20}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 8,
        "sl_pct": 6,
    },
]
