"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-08-04 14:52. Do not edit manually.

Launch config:
  DSR_TH = 0.8
  WFO_NET_GAIN_TH = 30
  WFO_DD_TH = 15
  WFO_R2_TH = 0.8
  WFO_WFR_TH = 0.6
  CORRELATION_DD_TH = 0.5
  MONTECARLO_RUIN_TH = 10
  MULTIVERSE_PVALUE_TH = 0.05

Train windows:
  6Hutc : 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
  12Hutc: 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
"""

STRATEGIES = [
    {
        "id": "05416_6Hutc_long_CLOSEgtMA20_AND_HISTVOL10gtSMA_HISTVOL20_AND_HISTVOL30gtSMA_HISTVOL20",
        "timeframe": "6Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "ma", "op": ">", "value": 20}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 20}, {"type": "histvol_regime", "period": 30, "op": ">", "sma_period": 20}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "12435_12Hutc_short_CLOSEltMA20_AND_CLOSEgtMA100_AND_HISTVOL30ltSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "ma", "op": "<", "value": 20}, {"type": "ma", "op": ">", "value": 100}, {"type": "histvol_regime", "period": 30, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 8,
        "sl_pct": 2,
    },
    {
        "id": "13931_12Hutc_short_HISTVOL10gtSMA_HISTVOL20_AND_HISTVOL10ltSMA_HISTVOL50_AND_HISTVOL30ltSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 20}, {"type": "histvol_regime", "period": 10, "op": "<", "sma_period": 50}, {"type": "histvol_regime", "period": 30, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 6,
        "sl_pct": 6,
    },
]
