"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-08-17 02:55. Do not edit manually.

Launch config:
  STEPM_K_PERCENTILE = 0.01
  WFO_NET_GAIN_TH = 30
  WFO_DD_TH = 15
  WFO_R2_TH = 0.7
  WFO_WFR_TH = 0.6
  CORRELATION_DD_TH = 0.55
  MONTECARLO_RUIN_TH = 10
  MULTIVERSE_PVALUE_TH = 0.05

Train windows:
  12Hutc: 2025-11-14 → 2026-08-14  (9m train)  |  next train: 2026-10-14  (+2m)
  4H    : 2025-11-14 → 2026-08-14  (9m train)  |  next train: 2026-10-14  (+2m)
  6Hutc : 2025-11-14 → 2026-08-14  (9m train)  |  next train: 2026-10-14  (+2m)
"""

STRATEGIES = [
    {
        "id": "02801_6Hutc_long_RSI7gt30_AND_RSI7lt50_AND_ADX21gt30",
        "timeframe": "6Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "rsi", "period": 7, "op": ">", "value": 30}, {"type": "rsi", "period": 7, "op": "<", "value": 50}, {"type": "adx", "period": 21, "op": ">", "value": 30}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 8,
        "sl_pct": 8,
    },
    {
        "id": "13463_4H_long_RSI7gt70_AND_CLOSEgtMA50_AND_HISTVOL30gtSMA_HISTVOL50",
        "timeframe": "4H",
        "active": True,
        "direction": "long",
        "specs": [{"type": "rsi", "period": 7, "op": ">", "value": 70}, {"type": "ma", "op": ">", "value": 50}, {"type": "histvol_regime", "period": 30, "op": ">", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "57481_12Hutc_long_CLOSEltCLOSEm10_AND_HISTVOL10ltSMA_HISTVOL20_AND_HISTVOL10gtSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "momentum", "op": "<", "value": 10}, {"type": "histvol_regime", "period": 10, "op": "<", "sma_period": 20}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "97355_12Hutc_short_RSI21gt50_AND_ADX21gt20_AND_ATR21ltSMA_ATR10",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 21, "op": ">", "value": 50}, {"type": "adx", "period": 21, "op": ">", "value": 20}, {"type": "atr_regime", "period": 21, "op": "<", "sma_period": 10}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 6,
        "sl_pct": 8,
    },
    {
        "id": "99558_12Hutc_short_RSI21lt50_AND_ATR7gtSMA_ATR10_AND_HISTVOL30ltSMA_HISTVOL20",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 21, "op": "<", "value": 50}, {"type": "atr_regime", "period": 7, "op": ">", "sma_period": 10}, {"type": "histvol_regime", "period": 30, "op": "<", "sma_period": 20}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 8,
        "sl_pct": 8,
    },
    {
        "id": "126056_4H_short_ATR7ltSMA_ATR30_AND_ATR21ltSMA_ATR30_AND_HISTVOL30gtSMA_HISTVOL50",
        "timeframe": "4H",
        "active": True,
        "direction": "short",
        "specs": [{"type": "atr_regime", "period": 7, "op": "<", "sma_period": 30}, {"type": "atr_regime", "period": 21, "op": "<", "sma_period": 30}, {"type": "histvol_regime", "period": 30, "op": ">", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 8,
        "sl_pct": 8,
    },
    {
        "id": "129539_6Hutc_short_ATR21gtSMA_ATR30_AND_HISTVOL20gtSMA_HISTVOL30_AND_HISTVOL20ltSMA_HISTVOL50",
        "timeframe": "6Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "atr_regime", "period": 21, "op": ">", "sma_period": 30}, {"type": "histvol_regime", "period": 20, "op": ">", "sma_period": 30}, {"type": "histvol_regime", "period": 20, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 8,
    },
]
