"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-08-14 15:30. Do not edit manually.

Launch config:
  WFO_NET_GAIN_TH = 30
  WFO_DD_TH = 15
  WFO_R2_TH = 0.7
  WFO_WFR_TH = 0.6
  CORRELATION_DD_TH = 0.6
  MONTECARLO_RUIN_TH = 10
  MULTIVERSE_PVALUE_TH = 0.05

Train windows:
  12Hutc: 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
  6Hutc : 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
"""

STRATEGIES = [
    {
        "id": "05416_12Hutc_long_CLOSEgtMA20_AND_HISTVOL10gtSMA_HISTVOL20_AND_HISTVOL20gtSMA_HISTVOL20",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "ma", "op": ">", "value": 20}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 20}, {"type": "histvol_regime", "period": 20, "op": ">", "sma_period": 20}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 8,
        "sl_pct": 8,
    },
    {
        "id": "09453_12Hutc_short_RSI14lt70_AND_ATR14gtSMA_ATR10_AND_ATR21ltSMA_ATR30",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 14, "op": "<", "value": 70}, {"type": "atr_regime", "period": 14, "op": ">", "sma_period": 10}, {"type": "atr_regime", "period": 21, "op": "<", "sma_period": 30}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 8,
        "sl_pct": 6,
    },
    {
        "id": "11731_12Hutc_short_ADX21gt20_AND_CLOSEgtMA100_AND_HISTVOL20ltSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "adx", "period": 21, "op": ">", "value": 20}, {"type": "ma", "op": ">", "value": 100}, {"type": "histvol_regime", "period": 20, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 6,
    },
    {
        "id": "13895_12Hutc_short_ATR21gtSMA_ATR30_AND_HISTVOL10ltSMA_HISTVOL50_AND_HISTVOL20ltSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "atr_regime", "period": 21, "op": ">", "sma_period": 30}, {"type": "histvol_regime", "period": 10, "op": "<", "sma_period": 50}, {"type": "histvol_regime", "period": 20, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 8,
        "sl_pct": 4,
    },
    {
        "id": "13897_6Hutc_short_ATR21gtSMA_ATR30_AND_HISTVOL20gtSMA_HISTVOL20_AND_HISTVOL20ltSMA_HISTVOL50",
        "timeframe": "6Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "atr_regime", "period": 21, "op": ">", "sma_period": 30}, {"type": "histvol_regime", "period": 20, "op": ">", "sma_period": 20}, {"type": "histvol_regime", "period": 20, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 100,
        "tp_pct": 10,
        "sl_pct": 8,
    },
]
