"""
Trading Strategies Configuration

This file defines all trading strategies used by the bot.
Each strategy must have all required parameters defined.

IMPORTANT:
- Strategy IDs must match those in IMPLEMENTED_STRATEGIES
- All strategies must be listed here even if inactive
- Parameter validation happens at bot startup
"""

STRATEGIES = [
    {
        'id': '02_reversal_long_4H',
        'name': 'reversal_long_4H',
        'timeframe': '4H',
        'active': True,
        'direction': 'long',
        'regime_trending': 0,
        'regime_ranging': 1.0,
        'regime_volatile': 0,
        'direction_mode': 'long_only',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 4,
        'tolerance': 20,
        'ma_period': 50,
        'tp_pct': 3,
        'sl_pct': 10
    },
    {
        'id': '03_parity_long_4H',
        'name': 'parity_long_4H',
        'timeframe': '4H',
        'active': True,
        'direction': 'long',
        'regime_trending': 1.0,
        'regime_ranging': 0,
        'regime_volatile': 0,
        'direction_mode': 'general',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 150,
        'tolerance': 40,
        'ma_period': 50,
        'tp_pct': 3,
        'sl_pct': 10
    },
    {
        'id': '04_reversal_short_4H',
        'name': 'reversal_short_4H',
        'timeframe': '4H',
        'active': True,
        'direction': 'short',
        'regime_trending': 1.0,
        'regime_ranging': 1.0,
        'regime_volatile': 1.0,
        'direction_mode': 'general',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 4,
        'tolerance': 25,
        'ma_period': 50,
        'tp_pct': 3,
        'sl_pct': 9
    },
    {
        'id': '06_reversal_long_1H',
        'name': 'reversal_long_1H',
        'timeframe': '1H',
        'active': True,
        'direction': 'long',
        'regime_trending': 1.0,
        'regime_ranging': 1.0,
        'regime_volatile': 1.0,
        'direction_mode': 'long_only',
        'sell_after_ncandles': 100,
        'order_amount': 200,
        'lookback': 7,
        'tolerance': 40,
        'ma_period': 25,
        'tp_pct': 2,
        'sl_pct': 10
    },
    {
        'id': '07_reversal_short_1H',
        'name': 'reversal_short_1H',
        'timeframe': '1H',
        'active': True,
        'direction': 'short',
        'regime_trending': 1.0,
        'regime_ranging': 1.0,
        'regime_volatile': 1.0,
        'direction_mode': 'general',
        'sell_after_ncandles': 100,
        'order_amount':200,
        'lookback': 5,
        'tolerance': 30,
        'ma_period': 50,
        'tp_pct': 1.9,
        'sl_pct': 5
    },
    {
        'id': '08_reversal_long_6Hutc',
        'name': 'reversal_long_6Hutc',
        'timeframe': '6Hutc',
        'active': True,
        'direction': 'long',
        'regime_trending': 1.0,
        'regime_ranging': 1.0,
        'regime_volatile': 0,
        'direction_mode': 'long_only',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 3,
        'tolerance': 20,
        'ma_period': 50,
        'tp_pct': 4,
        'sl_pct': 10
    },
    {
        'id': '09_reversal_short_6Hutc',
        'name': 'reversal_short_6Hutc',
        'timeframe': '6Hutc',
        'active': True,
        'direction': 'short',
        'regime_trending': 1.0,
        'regime_ranging': 1.0,
        'regime_volatile': 1.0,
        'direction_mode': 'general',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 6,
        'tolerance': 30,
        'ma_period': 25,
        'tp_pct': 4,
        'sl_pct': 7.5
    },
    {
        'id': '10_parity_long_1H',
        'name': 'parity_long_1H',
        'timeframe': '1H',
        'active': True,
        'direction': 'long',
        'regime_trending': 1.0,
        'regime_ranging': 0,
        'regime_volatile': 0,
        'direction_mode': 'long_only',
        'sell_after_ncandles': 75,
        'order_amount': 200,
        'lookback': 150,
        'tolerance': 15,
        'ma_period': 25,
        'tp_pct': 2,
        'sl_pct': 10
    },
    {
        'id': '11_parity_short_1H',
        'name': 'parity_short_1H',
        'timeframe': '1H',
        'active': True,
        'direction': 'short',
        'regime_trending': 1.0,
        'regime_ranging': 1.0,
        'regime_volatile': 1.0,
        'direction_mode': 'general',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 150,
        'tolerance': 20,
        'ma_period': 50,
        'tp_pct': 2,
        'sl_pct': 7.5
    },
    {
        'id': '12_parity_long_6Hutc',
        'name': 'parity_long_6Hutc',
        'timeframe': '6Hutc',
        'active': True,
        'direction': 'long',
        'regime_trending': 1.0,
        'regime_ranging': 1.0,
        'regime_volatile': 0,
        'direction_mode': 'long_only',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 50,
        'tolerance': 40,
        'ma_period': 25,
        'tp_pct': 3.5,
        'sl_pct': 10
    },
    {
        'id': '13_orderblocks_short_4H',
        'name': 'orderblocks_short_4H',
        'timeframe': '4H',
        'active': True,
        'direction': 'short',
        'regime_trending': 0,
        'regime_ranging': 1.0,
        'regime_volatile': 0,
        'direction_mode': 'general',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 50,
        'tolerance': 35,
        'impulse': 0.01,
        'tp_pct': 4,
        'sl_pct': 11
    },
    {
        'id': '16_ranging_short_6Hutc',
        'name': 'ranging_short_6Hutc',
        'timeframe': '6Hutc',
        'active': True,
        'direction': 'short',
        'regime_trending': 1.0,
        'regime_ranging': 1.0,
        'regime_volatile': 1.0,
        'direction_mode': 'general',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 10,
        'tolerance': 5,
        'range': 25,
        'tp_pct': 4,
        'sl_pct': 6
    },
    {
        'id': '17_flag_long_4H',
        'name': 'flag_long_4H',
        'timeframe': '4H',
        'active': True,
        'direction': 'long',
        'regime_trending': 1.0,
        'regime_ranging': 1.0,
        'regime_volatile': 1.0,
        'direction_mode': 'general',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 13,
        'impulse': 5,
        'flag': 40,
        'ma_period': 50,
        'tp_pct': 4,
        'sl_pct': 10
    },
    {
        'id': '19_flag_short_4H',
        'name': 'flag_short_4H',
        'timeframe': '4H',
        'active': True,
        'direction': 'short',
        'regime_trending': 1.0,
        'regime_ranging': 1.0,
        'regime_volatile': 1.0,
        'direction_mode': 'general',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 10,
        'impulse': 3,
        'flag': 50,
        'ma_period': 50,
        'tp_pct': 3,
        'sl_pct': 9
    },
    {
        'id': '20_flag_short_1H',
        'name': 'flag_short_1H',
        'timeframe': '1H',
        'active': True,
        'direction': 'short',
        'regime_trending': 1.0,
        'regime_ranging': 1.0,
        'regime_volatile': 1.0,
        'direction_mode': 'general',
        'sell_after_ncandles': 50,
        'order_amount': 200,
        'lookback': 20,
        'impulse': 3,
        'flag': 60,
        'ma_period': 25,
        'tp_pct': 2,
        'sl_pct': 8
    },
]