"""
Rule Mining Strategies Configuration — Deploy

Auto-generated by run_deploy_rule on 2026-07-26 22:41. Do not edit manually.

Train windows:
  12Hutc: 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
  6Hutc : 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
  4H    : 2025-10-23 → 2026-07-23  (9m train)  |  next train: 2026-09-23  (+2m)
  DSR_TH               = 0.80
  WFO_NET_GAIN_TH      = 40
  WFO_DD_TH            = 20
  WFO_R2_TH            = 0.8
  WFO_WFR_TH           = 0.6
  CORRELATION_DD_TH    = 0.55
  MONTECARLO_RUIN_TH   = 10
  MULTIVERSE_PVALUE_TH = 0.05
"""

STRATEGIES = [
    {
        "id": "26749_6Hutc_long_CLOSEgtMA20_AND_HISTVOL10gtSMA_HISTVOL20_AND_HISTVOL30gtSMA_HISTVOL20",
        "timeframe": "6Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "ma", "op": ">", "value": 20}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 20}, {"type": "histvol_regime", "period": 30, "op": ">", "sma_period": 20}],
        "sell_after_ncandles": 50,
        "order_amount": 280,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "29493_12Hutc_long_CLOSEltCLOSEm10_AND_HISTVOL10ltSMA_HISTVOL20_AND_HISTVOL10gtSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "long",
        "specs": [{"type": "momentum", "op": "<", "value": 10}, {"type": "histvol_regime", "period": 10, "op": "<", "sma_period": 20}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 280,
        "tp_pct": 10,
        "sl_pct": 8,
    },
    {
        "id": "34983_6Hutc_short_RSI7lt30_AND_CLOSEltMA100_AND_ATR21ltSMA_ATR50",
        "timeframe": "6Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 7, "op": "<", "value": 30}, {"type": "ma", "op": "<", "value": 100}, {"type": "atr_regime", "period": 21, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 280,
        "tp_pct": 8,
        "sl_pct": 6,
    },
    {
        "id": "37676_12Hutc_short_RSI7lt50_AND_CLOSEgtMA100_AND_HISTVOL30ltSMA_HISTVOL50",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 7, "op": "<", "value": 50}, {"type": "ma", "op": ">", "value": 100}, {"type": "histvol_regime", "period": 30, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 280,
        "tp_pct": 8,
        "sl_pct": 8,
    },
    {
        "id": "37754_4H_short_RSI7lt50_AND_CLOSEgtCLOSEm10_AND_ATR7ltSMA_ATR10",
        "timeframe": "4H",
        "active": True,
        "direction": "short",
        "specs": [{"type": "rsi", "period": 7, "op": "<", "value": 50}, {"type": "momentum", "op": ">", "value": 10}, {"type": "atr_regime", "period": 7, "op": "<", "sma_period": 10}],
        "sell_after_ncandles": 50,
        "order_amount": 280,
        "tp_pct": 6,
        "sl_pct": 6,
    },
    {
        "id": "54239_6Hutc_short_ADX14gt20_AND_CLOSEgtMA100_AND_ATR14ltSMA_ATR50",
        "timeframe": "6Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "adx", "period": 14, "op": ">", "value": 20}, {"type": "ma", "op": ">", "value": 100}, {"type": "atr_regime", "period": 14, "op": "<", "sma_period": 50}],
        "sell_after_ncandles": 50,
        "order_amount": 280,
        "tp_pct": 10,
        "sl_pct": 6,
    },
    {
        "id": "59326_12Hutc_short_CLOSEltMA100_AND_ATR21ltSMA_ATR10_AND_HISTVOL10gtSMA_HISTVOL20",
        "timeframe": "12Hutc",
        "active": True,
        "direction": "short",
        "specs": [{"type": "ma", "op": "<", "value": 100}, {"type": "atr_regime", "period": 21, "op": "<", "sma_period": 10}, {"type": "histvol_regime", "period": 10, "op": ">", "sma_period": 20}],
        "sell_after_ncandles": 50,
        "order_amount": 280,
        "tp_pct": 6,
        "sl_pct": 8,
    },
]
