"""
strategies_loop_00.py — Batch loop configuration.
Edit param_grid, n_symbols and order_amount before each run.
This file is NOT updated by the batch automatically.
"""

STRATEGIES_LOOP = [
    {
        "id": "30_reversal_long_1H",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [10],
            "TOLERANCE": [10],
            "MA_PERIOD": [25],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "31_reversal_long_30m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [10],
            "TOLERANCE": [10],
            "MA_PERIOD": [25],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "32_reversal_long_15m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [10],
            "TOLERANCE": [10],
            "MA_PERIOD": [25],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "33_reversal_short_1H",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [8],
            "TOLERANCE": [30],
            "MA_PERIOD": [25],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "34_reversal_short_30m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [8],
            "TOLERANCE": [10],
            "MA_PERIOD": [25],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "36_parity_long_1H",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [50],
            "TOLERANCE": [10],
            "MA_PERIOD": [25],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "37_parity_long_30m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [50],
            "TOLERANCE": [10],
            "MA_PERIOD": [25],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "38_parity_long_15m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [50],
            "TOLERANCE": [10],
            "MA_PERIOD": [25],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "39_parity_short_1H",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [100],
            "TOLERANCE": [10],
            "MA_PERIOD": [25],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "40_parity_short_30m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [50],
            "TOLERANCE": [10],
            "MA_PERIOD": [25],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "41_parity_short_15m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [50],
            "TOLERANCE": [10],
            "MA_PERIOD": [25],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "42_flag_long_1H",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [20],
            "MA_PERIOD": [50],
            "IMPULSE": [6],
            "FLAG": [20],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "43_flag_long_30m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [20],
            "MA_PERIOD": [50],
            "IMPULSE": [6],
            "FLAG": [40],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "44_flag_long_15m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [20],
            "MA_PERIOD": [50],
            "IMPULSE": [6],
            "FLAG": [60],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "45_flag_short_1H",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [60],
            "MA_PERIOD": [25],
            "IMPULSE": [6],
            "FLAG": [40],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "46_flag_short_30m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [60],
            "MA_PERIOD": [25],
            "IMPULSE": [4],
            "FLAG": [20],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "47_flag_short_15m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [100],
            "LOOKBACK": [20],
            "MA_PERIOD": [50],
            "IMPULSE": [6],
            "FLAG": [40],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "48_orderblocks_long_1H",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [30],
            "TOLERANCE": [25],
            "IMPULSE": [0.08],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "49_orderblocks_long_30m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [30],
            "TOLERANCE": [25],
            "IMPULSE": [0.08],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "50_orderblocks_long_15m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [30],
            "TOLERANCE": [20],
            "IMPULSE": [0.08],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "51_orderblocks_short_1H",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [30],
            "TOLERANCE": [20],
            "IMPULSE": [0.08],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "52_orderblocks_short_30m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [30],
            "TOLERANCE": [20],
            "IMPULSE": [0.02],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
    {
        "id": "53_orderblocks_short_15m",
        "n_symbols": 11,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [30],
            "TOLERANCE": [20],
            "IMPULSE": [0.08],
            "TP_PCT": [2.0],
            "SL_PCT": [3.0],
        },
    },
]
