"""
strategies_loop.py — Batch loop configuration.
Edit param_grid, n_symbols and order_amount before each run.
This file is NOT updated by the batch automatically.
"""

STRATEGIES_LOOP = [
    {
        "id": "02_reversal_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [3,4,5],
            "TOLERANCE": [20,30,40],
            "MA_PERIOD": [50],
            "TP_PCT": [2,3,4],
            "SL_PCT": [8,9,10],
        },
    },
    {
        "id": "03_parity_long_4H",
        "n_symbols": 9,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50,100,150],
            "TOLERANCE": [20,30,40],
            "MA_PERIOD": [50],
            "TP_PCT": [2,3,4],
            "SL_PCT": [8,9,10],
        },
    },
    {
        "id": "04_reversal_short_4H",
        "n_symbols": 30,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [3,4,5],
            "TOLERANCE": [25,35,45],
            "MA_PERIOD": [50],
            "TP_PCT": [2,3,4],
            "SL_PCT": [7,8,9],
        },
    },
    {
        "id": "06_reversal_long_1H",
        "n_symbols": 8,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [100],
            "LOOKBACK": [6,7,8],
            "TOLERANCE": [5,10,20],
            "MA_PERIOD": [25,50],
            "TP_PCT": [2,3,4],
            "SL_PCT": [8,9,10],
        },
    },
    {
        "id": "07_reversal_short_1H",
        "n_symbols": 8,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [100],
            "LOOKBACK": [6,7,8],
            "TOLERANCE": [5,10,20],
            "MA_PERIOD": [25,50],
            "TP_PCT": [2,3,4],
            "SL_PCT": [6,7,8],
        },
    },
    {
        "id": "08_reversal_long_6Hutc",
        "n_symbols": 8,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [3,4,5],
            "TOLERANCE": [10,20,30],
            "MA_PERIOD": [25,50],
            "TP_PCT": [4,5,6],
            "SL_PCT": [7,8,9],
        },
    },
    {
        "id": "09_reversal_short_6Hutc",
        "n_symbols": 30,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [3,4,5],
            "TOLERANCE": [20,30,40],
            "MA_PERIOD": [25,50],
            "TP_PCT": [2,3,4],
            "SL_PCT": [8,9,10],
        },
    },
    {
        "id": "10_parity_long_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [75],
            "LOOKBACK": [50,100,150],
            "TOLERANCE": [5,10,20],
            "MA_PERIOD": [25,50],
            "TP_PCT": [2,3,4],
            "SL_PCT": [8,9,10],
        },
    },
    {
        "id": "11_parity_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [25,50,100],
            "TOLERANCE": [5,10,20],
            "MA_PERIOD": [25,50],
            "TP_PCT": [2,3,4],
            "SL_PCT": [7,8,9],
        },
    },
    {
        "id": "12_parity_long_6Hutc",
        "n_symbols": 15,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [25,50,100],
            "TOLERANCE": [30,40,50],
            "MA_PERIOD": [25,50],
            "TP_PCT": [3,4,5],
            "SL_PCT": [8,9,10],
        },
    },
    {
        "id": "13_orderblocks_short_4H",
        "n_symbols": 30,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50,100,150],
            "TOLERANCE": [30,40,50],
            "IMPULSE": [0.05,0.1,0.2],
            "TP_PCT": [2,3,4],
            "SL_PCT": [7,8,9],
        },
    },
    {
        "id": "16_ranging_short_6Hutc",
        "n_symbols": 30,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [8,9,10],
            "TOLERANCE": [5,10,15],
            "RANGES": [30,40,50],
            "TP_PCT": [3,4,5],
            "SL_PCT": [8,9,10],
        },
    },
    {
        "id": "17_flag_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20,50,100],
            "MA_PERIOD": [50],
            "IMPULSE": [4,5,6,10],
            "FLAG": [30,40,50],
            "TP_PCT": [2,3,4],
            "SL_PCT": [8,9,10],
        },
    },
    {
        "id": "19_flag_short_4H",
        "n_symbols": 20,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [5,10,15],
            "MA_PERIOD": [50],
            "IMPULSE": [1,2,3],
            "FLAG": [50,60,70],
            "TP_PCT": [2,3,4],
            "SL_PCT": [7,8,9],
        },
    },
    {
        "id": "20_flag_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [10,20,30,40],
            "MA_PERIOD": [25,50],
            "IMPULSE": [2,3,4,5],
            "FLAG": [20,40,60,80],
            "TP_PCT": [2,3,4,5,6],
            "SL_PCT": [5,6,7,8,9,10],
        },
    },
]
