"""
strategies_loop.py — Batch loop configuration.

Edit param_grid, n_symbols and order_amount before each run.
This file is NOT updated by the batch automatically.
"""

STRATEGIES_LOOP = [
    {
        "strategy_id": "02_reversal_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [4],
            "TP_PCT": [3],
            "MA_PERIOD": [50],
            "TOLERANCE": [20],
            "SL_PCT": [10],
        },
    },
    {
        "strategy_id": "03_parity_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [150],
            "TP_PCT": [3],
            "MA_PERIOD": [50],
            "TOLERANCE": [40],
            "SL_PCT": [10],
        },
    },
    {
        "strategy_id": "04_reversal_short_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [4],
            "TP_PCT": [3],
            "MA_PERIOD": [50],
            "TOLERANCE": [25],
            "SL_PCT": [9],
        },
    },
    {
        "strategy_id": "06_reversal_long_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [100],
            "LOOKBACK": [7],
            "TP_PCT": [2],
            "MA_PERIOD": [25],
            "TOLERANCE": [40],
            "SL_PCT": [10],
        },
    },
    {
        "strategy_id": "07_reversal_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [100],
            "LOOKBACK": [5],
            "TP_PCT": [2.0],
            "MA_PERIOD": [50],
            "TOLERANCE": [30],
            "SL_PCT": [5],
        },
    },
    {
        "strategy_id": "08_reversal_long_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [3],
            "TP_PCT": [4],
            "MA_PERIOD": [50],
            "TOLERANCE": [20],
            "SL_PCT": [10],
        },
    },
    {
        "strategy_id": "09_reversal_short_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [6],
            "TP_PCT": [4],
            "MA_PERIOD": [25],
            "TOLERANCE": [30],
            "SL_PCT": [7.5],
        },
    },
    {
        "strategy_id": "10_parity_long_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [75],
            "LOOKBACK": [150],
            "TP_PCT": [2],
            "MA_PERIOD": [25],
            "TOLERANCE": [15],
            "SL_PCT": [10],
        },
    },
    {
        "strategy_id": "11_parity_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [150],
            "TP_PCT": [2],
            "MA_PERIOD": [50],
            "TOLERANCE": [20],
            "SL_PCT": [7.5],
        },
    },
    {
        "strategy_id": "12_parity_long_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [50],
            "TP_PCT": [3.5],
            "MA_PERIOD": [25],
            "TOLERANCE": [40],
            "SL_PCT": [10],
        },
    },
    {
        "strategy_id": "13_orderblocks_short_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [50],
            "TP_PCT": [4],
            "IMPULSE": [0.01],
            "TOLERANCE": [35],
            "SL_PCT": [11],
        },
    },
    {
        "strategy_id": "16_ranging_short_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [10],
            "TP_PCT": [4],
            "RANGES": [25],
            "TOLERANCE": [5],
            "SL_PCT": [6],
        },
    },
    {
        "strategy_id": "17_flag_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [13],
            "TP_PCT": [4],
            "IMPULSE": [5],
            "MA_PERIOD": [50],
            "FLAG": [40],
            "SL_PCT": [10],
        },
    },
    {
        "strategy_id": "19_flag_short_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [10],
            "TP_PCT": [3],
            "IMPULSE": [3],
            "MA_PERIOD": [50],
            "FLAG": [50],
            "SL_PCT": [9],
        },
    },
    {
        "strategy_id": "20_flag_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [20],
            "TP_PCT": [2],
            "IMPULSE": [3],
            "MA_PERIOD": [25],
            "FLAG": [60],
            "SL_PCT": [8],
        },
    },
]
