"""
strategies_loop.py — Batch loop configuration.
Edit param_grid, n_symbols and order_amount before each run.
This file is NOT updated by the batch automatically.
"""

STRATEGIES_LOOP = [
    {
        "id": "02_reversal_long_4H",
        "n_symbols": 32,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [2,3,4,5,6],
            "TOLERANCE": [10,20,30,40],
            "MA_PERIOD": [50],
            "TP_PCT": [2,3,4,5],
            "SL_PCT": [5,6,7,8,9,10],
        },
    },
    {
        "id": "03_parity_long_4H",
        "n_symbols": 9,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [50,100,150],
            "TOLERANCE": [10,20,30,40],
            "MA_PERIOD": [50],
            "TP_PCT": [2,3,4,5],
            "SL_PCT": [5,6,7,8,9,10],
        },
    },
    {
        "id": "04_reversal_short_4H",
        "n_symbols": 32,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [2,3,4,5,6],
            "TOLERANCE": [10,20,25,35],
            "MA_PERIOD": [50],
            "TP_PCT": [2,3,4,5],
            "SL_PCT": [5,6,7,8,9,10],
        },
    },
    {
        "id": "06_reversal_long_1H",
        "n_symbols": 8,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [100],
            "LOOKBACK": [4,5,6,7],
            "TOLERANCE": [10,20,30,40],
            "MA_PERIOD": [25,50],
            "TP_PCT": [2,3,4,5],
            "SL_PCT": [5,6,7,8,910],
        },
    },
    {
        "id": "07_reversal_short_1H",
        "n_symbols": 8,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50,100,150],
            "LOOKBACK": [3,4,5,6,7],
            "TOLERANCE": [10,20,30,40],
            "MA_PERIOD": [25,50],
            "TP_PCT": [2,3,4,5],
            "SL_PCT": [4,5,6,7,8,9],
        },
    },
    {
        "id": "08_reversal_long_6Hutc",
        "n_symbols": 8,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [3,4,5,6],
            "TOLERANCE": [10,20,30,40],
            "MA_PERIOD": [25,50],
            "TP_PCT": [2,3,4,5],
            "SL_PCT": [5,6,7,8,9,10],
        },
    },
    {
        "id": "09_reversal_short_6Hutc",
        "n_symbols": 31,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [4,5,6,7,8],
            "TOLERANCE": [10,20,30,40],
            "MA_PERIOD": [25,50],
            "TP_PCT": [2,3,4,5],
            "SL_PCT": [5,6,7,8,9,10],
        },
    },
    {
        "id": "10_parity_long_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [75],
            "LOOKBACK": [150],
            "TOLERANCE": [15],
            "MA_PERIOD": [25],
            "TP_PCT": [2],
            "SL_PCT": [10],
        },
    },
    {
        "id": "11_parity_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [150],
            "TOLERANCE": [20],
            "MA_PERIOD": [50],
            "TP_PCT": [2],
            "SL_PCT": [7.5],
        },
    },
    {
        "id": "12_parity_long_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [50],
            "TOLERANCE": [40],
            "MA_PERIOD": [25],
            "TP_PCT": [3.5],
            "SL_PCT": [10],
        },
    },
    {
        "id": "13_orderblocks_short_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [50],
            "TOLERANCE": [35],
            "IMPULSE": [0.01],
            "TP_PCT": [4],
            "SL_PCT": [11],
        },
    },
    {
        "id": "16_ranging_short_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [10],
            "TOLERANCE": [5],
            "RANGES": [25],
            "TP_PCT": [4],
            "SL_PCT": [6],
        },
    },
    {
        "id": "17_flag_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [13],
            "MA_PERIOD": [50],
            "IMPULSE": [5],
            "FLAG": [40],
            "TP_PCT": [4],
            "SL_PCT": [10],
        },
    },
    {
        "id": "19_flag_short_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [10],
            "MA_PERIOD": [50],
            "IMPULSE": [3],
            "FLAG": [50],
            "TP_PCT": [3],
            "SL_PCT": [9],
        },
    },
    {
        "id": "20_flag_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [20],
            "MA_PERIOD": [25],
            "IMPULSE": [3],
            "FLAG": [60],
            "TP_PCT": [2],
            "SL_PCT": [8],
        },
    },
]
