#shared_batch/utils/io.py
import importlib.util
import logging
import os
import pandas as pd
from shared_batchs.registry.signal_registry import SIGNAL_PARAM_KEYS, PARAM_KEYS
from datetime import datetime

logger = logging.getLogger("BOT_batch.utils.io")

# =============================================================================
# PRIVATE HELPERS
# =============================================================================

def _fmt_py_val(val) -> str:
    """Format a Python value for writing into a .py file."""
    if isinstance(val, bool):
        return str(val)
    if isinstance(val, str):
        return f'"{val}"'
    return str(val)


def _load_py_module(path: str, module_name: str):
    """Load a .py file as a module and return it."""
    spec = importlib.util.spec_from_file_location(module_name, path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod
# =============================================================================
# BINS
# =============================================================================
def load_regime_bins(bins_path: str, strategy_id: str) -> set:
    """
    Load precomputed regime bins for a strategy from a generated regime_bins_{SET}.py file.
    Returns empty set if file not found or strategy not present.
    """
    if not os.path.exists(bins_path):
        logger.warning(f"⚠️  regime_bins file not found: {bins_path} — using empty bins.")
        return set()
    mod  = _load_py_module(bins_path, "regime_bins")
    bins = getattr(mod, "REGIME_BINS", {})
    return set(bins.get(strategy_id, set()))
# =============================================================================
# SAVE DRIFT REFERENCE
# =============================================================================

def save_drift_reference(drift_results: list, output_path: str) -> None:
    """
    Write drift_reference_batch.py with p_target winrate reference values
    from regime OOS1 backtest results.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    lines = [
        '"""',
        'Regime OOS1 reference values for drift detection.',
        'P_TARGET_WINRATE: Observed winrate on regime-filtered OOS1 trades (used as binomial p_target)',
        f'Auto-generated by BOT_batch on {datetime.now().strftime("%Y-%m-%d %H:%M")}. Do not edit manually.',
        '"""',
        'DRIFT_REFERENCE = {',
    ]
    for entry in drift_results:
        lines += [
            f"    '{entry['strategy_id']}': {{",
            f"        'p_target_winrate': {entry['p_target_winrate']},",
            f"    }},",
        ]
    lines.append("}")
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    logger.debug(f"drift_reference_batch.py updated → {output_path}")


# =============================================================================
# SAVE STRATEGIES PR BATCH
# =============================================================================

def save_strategies_pr(
    strategies_batch_path: str,
    output_path: str,
    validation_results: list,
    best_params_map: dict,
    strategy_ids_to_run: list = None,
    module_name: str = "strategies_BT_batch",
) -> None:
    """
    Generate strategies_PR_batch.py for production deployment.
    Reads strategies_BT_batch.py (never modified), applies dynamic fields from memory.
    """
    if not os.path.exists(strategies_batch_path):
        logger.warning(f"⚠️  {os.path.basename(strategies_batch_path)} not found — skipping.")
        return

    strategies = _load_py_module(strategies_batch_path, module_name).STRATEGIES
    if strategy_ids_to_run is not None:
        strategies = [s for s in strategies if s["id"] in strategy_ids_to_run]

    val_map = {v["strategy_id"]: v for v in validation_results}

    all_bins = [
        "regime_trending_uptrend",
        "regime_trending_dwtrend",
        "regime_ranging_uptrend",
        "regime_ranging_dwtrend",
        "regime_volatile_uptrend",
        "regime_volatile_dwtrend",
    ]

    pr_lines = [
        '"""',
        'Trading Strategies Configuration',
        '',
        f'Auto-generated by BOT_batch on {datetime.now().strftime("%Y-%m-%d %H:%M")}. Do not edit manually.',
        'Copy to BOT_trading/config/strategies_00/E1.py to deploy.',
        '"""',
        '',
        'STRATEGIES = [',
    ]

    for s in strategies:
        sid     = s["id"]
        v       = val_map.get(sid, {})
        bp      = best_params_map.get(sid, {})
        updated = dict(s)

        if v:
            updated["active"] = "VALIDATED" in v["verdict"]
            bins_to_filter    = v.get("bins_to_filter", set())
        else:
            bins_to_filter = set()

        if bp:
            for k, val in bp.items():
                updated[k.lower()] = val

        pr_lines.append("    {")
        pr_lines.append(f'        "id": "{sid}",')
        pr_lines.append(f'        "name": "{updated["name"]}",')
        pr_lines.append(f'        "timeframe": "{updated["timeframe"]}",')
        pr_lines.append(f'        "active": {updated.get("active", False)},')
        pr_lines.append(f'        "direction": "{updated["direction"]}",')

        for bin_key in all_bins:
            family, direction = bin_key.replace("regime_", "").rsplit("_", 1)
            blocked = f"{family}_{direction}" in bins_to_filter
            pr_lines.append(f'        "{bin_key}": {0 if blocked else 1},')

        pr_lines.append(f'        "sell_after_ncandles": {updated.get("sell_after_ncandles", 0)},')
        pr_lines.append(f'        "order_amount": {updated.get("order_amount_prod", 200)},')

        for k in SIGNAL_PARAM_KEYS:
            if k in updated:
                pr_lines.append(f'        "{k}": {_fmt_py_val(updated[k])},')

        for k in ("tp_pct", "sl_pct"):
            if k in updated:
                pr_lines.append(f'        "{k}": {_fmt_py_val(updated[k])},')

        pr_lines.append("    },")

    pr_lines.append("]")

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(pr_lines) + "\n")

    logger.info(f"\n{'─'*115}\n  ✅ strategies_OO/E1_batch.py generated\n{'─'*115}")


# =============================================================================
# COMPARE BATCH VS PR_BATCH AND GENERATE CSV
# =============================================================================

def compare_and_generate_csv(
    strategies_batch_path: str,
    pr_batch_path: str,
    csv_path: str,
) -> None:
    """
    Compare strategies_batch.py (previous state) vs strategies_NN_batch.py (new state).
    Generate strategies_params.csv with change columns for diagnostics.
    """
    if not os.path.exists(strategies_batch_path):
        logger.warning(f"⚠️  strategies_batch.py not found — skipping CSV generation.")
        return
    if not os.path.exists(pr_batch_path):
        logger.warning(f"⚠️  strategies_NN_batch.py not found — skipping CSV generation.")
        return

    prev_map = {s["id"]: s for s in _load_py_module(strategies_batch_path, "strategies_batch").STRATEGIES}
    new_map  = {s["id"]: s for s in _load_py_module(pr_batch_path, "strategies_pr_batch").STRATEGIES}

    regime_bin_keys = (
        "regime_trending_uptrend", "regime_trending_dwtrend",
        "regime_ranging_uptrend",  "regime_ranging_dwtrend",
        "regime_volatile_uptrend", "regime_volatile_dwtrend",
    )

    rows = []
    for sid, new in new_map.items():
        prev = prev_map.get(sid, {})

        prev_active   = prev.get("active", False)
        new_active    = new.get("active", False)
        change_active = (
            f"{'True' if prev_active else 'False'}→{'True' if new_active else 'False'}"
            if prev_active != new_active else "N/A"
        )

        param_changes = []
        for k in PARAM_KEYS:
            prev_val = prev.get(k)
            new_val  = new.get(k)
            if prev_val is not None and new_val is not None and prev_val != new_val:
                param_changes.append(f"{k}: {prev_val}→{new_val}")
        change_params = " | ".join(param_changes) if param_changes else "N/A"

        regime_changes = []
        for bin_key in regime_bin_keys:
            prev_val = prev.get(bin_key)
            new_val  = new.get(bin_key)
            if prev_val is not None and new_val is not None and float(prev_val) != float(new_val):
                regime_changes.append(f"{bin_key}: {prev_val}→{new_val}")
        change_regime = " | ".join(regime_changes) if regime_changes else "N/A"

        row = {
            "id":                  sid,
            "name":                new["name"],
            "timeframe":           new["timeframe"],
            "active":              new_active,
            "direction":           new["direction"],
            "sell_after_ncandles": new.get("sell_after_ncandles", 0),
            "order_amount":        new.get("order_amount", 240),
            "lookback":            new.get("lookback"),
            "tolerance":           new.get("tolerance"),
            "ma_period":           new.get("ma_period"),
            "tp_pct":              new.get("tp_pct"),
            "sl_pct":              new.get("sl_pct"),
            "impulse":             new.get("impulse"),
            "flag":                new.get("flag"),
            "last_run":            pd.Timestamp.now().strftime("%Y-%m-%d %H:%M"),
            "validated":           new_active,
            "last_change_active":  change_active,
            "last_change_params":  change_params,
            "last_change_regime":  change_regime,
        }
        for bin_key in regime_bin_keys:
            row[bin_key] = new.get(bin_key, 1.0)

        rows.append(row)

    os.makedirs(os.path.dirname(csv_path), exist_ok=True)
    pd.DataFrame(rows).to_csv(csv_path, index=False)
    logger.debug(f"✅ strategies_params.csv generated → {csv_path}")


# =============================================================================
# UPDATE STRATEGIES SYMBOLS
# =============================================================================

def update_strategies_symbols(
    strategy_id: str,
    symbols_oos_final: list,
    timeframe: str = None,
    symbols_live_folder: str = None,
) -> dict:
    symbols_changed = False

    if timeframe and symbols_live_folder:
        os.makedirs(symbols_live_folder, exist_ok=True)
        live_filename = f"symbols_live_{strategy_id}_{timeframe}.csv"
        live_path     = os.path.join(symbols_live_folder, live_filename)

        if os.path.exists(live_path):
            prev_symbols    = pd.read_csv(live_path, header=None)[0].tolist()
            symbols_changed = prev_symbols != list(symbols_oos_final)
        else:
            symbols_changed = True

        pd.DataFrame(symbols_oos_final).to_csv(live_path, index=False, header=False)
        logger.debug(f"symbols_live saved → {live_path}")

    if symbols_changed:
        logger.debug(f"🔵 symbols_live — symbols updated for '{strategy_id}'")
    else:
        logger.debug(f"⚪ symbols_live — symbols unchanged for '{strategy_id}'")

    return {"symbols_changed": symbols_changed}


# =============================================================================
# ACCUMULATE STRATEGY TRADES
# =============================================================================

def accumulate_strategy_trades(
    registry: list,
    strategy_id: str,
    trade_log: pd.DataFrame,
    csv_folder: str = None,
    label: str = "",
) -> None:
    registry.append((strategy_id, trade_log.copy()))
    if csv_folder and label:
        os.makedirs(csv_folder, exist_ok=True)
        path               = os.path.join(csv_folder, f"trades_{label}_{strategy_id}.csv")
        df_out             = trade_log.copy()
        df_out["strategy"] = strategy_id
        df_out.to_csv(path, index=False)
        logger.debug(f"trades saved → {path}")


# =============================================================================
# PRINT UPDATE STATUS
# =============================================================================

def print_update_status(
    csv_path: str,
    symbols_live_folder: str,
    validation_results: list,
) -> None:
    """
    Print update status tables reading from CSV:
      1. Active
      2. Params
      3. Market Regime
      4. Symbols
    """
    if not validation_results:
        return

    if not os.path.exists(csv_path):
        logger.warning(f"⚠️  strategies_params.csv not found — skipping update status tables.")
        return

    df           = pd.read_csv(csv_path)
    strategy_ids = [v["strategy_id"] for v in validation_results]
    df           = df[df["id"].isin(strategy_ids)].set_index("id")

    def _get(sid, col, default="—"):
        try:
            val = df.loc[sid, col]
            return str(val) if pd.notna(val) else default
        except KeyError:
            return default

    def _active_icon(sid):
        val = _get(sid, "active")
        if val == "True":  return "🟢 active"
        if val == "False": return "🔴 inactive"
        return "—"

    def _change_icon(val):
        if val in ("N/A", "—", ""):  return "⚪ no change"
        return f"🔵 {val}"

    # Table 1 — Active
    lines = [
        f"\n{'─'*115}", f"  ACTIVE", f"{'─'*115}",
        f"  {'Strategy':<27} {'Status':<16} {'Changes':<35}",
        f"  {'-'*103}",
    ]
    for sid in strategy_ids:
        change = _get(sid, "last_change_active")
        lines.append(f"  {sid:<27} {_active_icon(sid):<16} {_change_icon(change):<35}")
    lines.append(f"  {'─'*115}")
    logger.info("\n".join(lines))

    # Table 2 — Params
    lines = [
        f"\n{'─'*115}", f"  PARAMS", f"{'─'*115}",
        f"  {'Strategy':<27} {'Changes':<50}",
        f"  {'-'*103}",
    ]
    for sid in strategy_ids:
        change = _get(sid, "last_change_params")
        lines.append(f"  {sid:<27} {_change_icon(change):<50}")
    lines.append(f"  {'-'*103}")
    logger.info("\n".join(lines))

    # Table 3 — Market Regime
    lines = [
        f"\n{'─'*115}", f"  MARKET REGIME", f"{'─'*115}",
        f"  {'Strategy':<27} {'Trending':>10} {'Ranging':>10} {'Volatile':>10} {'Changes':<40}",
        f"  {'-'*103}",
    ]
    for sid in strategy_ids:
        trending = _get(sid, "regime_trending")
        ranging  = _get(sid, "regime_ranging")
        volatile = _get(sid, "regime_volatile")
        change   = _get(sid, "last_change_regime")
        lines.append(
            f"  {sid:<27} {trending:>10} {ranging:>10} {volatile:>10} {_change_icon(change):<40}"
        )
    lines.append(f"  {'─'*115}")
    logger.info("\n".join(lines))

    # Table 4 — Symbols
    lines = [
        f"\n{'─'*115}", f"  SYMBOLS", f"{'─'*115}",
        f"  {'Strategy':<27} {'Status':<16}",
        f"  {'-'*103}",
    ]
    for v in validation_results:
        sid  = v["strategy_id"]
        icon = "🔵 updated" if v.get("symbols_changed") else "⚪ no change"
        lines.append(f"  {sid:<27} {icon:<16}")
    lines.append(f"  {'─'*103}")
    logger.info("\n".join(lines))