"""
regime_BINS_00.py — Regime classification bins. Do not edit manually.
Generated by regime_GE_calibration.py — ATR_NORM(10)>=0.02 | ER(20)>=0.6 | MODE=OR
Auto-generated on 2026-06-01 09:29 UTC.
"""

INDICATORS: dict[str, dict] = {
    "atr_norm": {
        "windows":    [10],
        "thresholds": [0.02],
        "enabled":    True,
    },
    "er": {
        "windows":    [20],
        "thresholds": [0.6],
        "enabled":    True,
    },
}
COMBINE_MODE          = "OR"
ANALYSIS_MODE         = "SYMBOL"
REGIME_TIMEFRAME_MODE = "DAILY"

OPTIMIZE_METRIC       = "calmar"
CLASSIFICATION_MODE   = "strict"

REGIME_BINS = {
    "01_reversal_long_15m": "ranging",
    "02_reversal_short_15m": "neutral",
    "03_reversal_long_30m": "neutral",
    "04_reversal_short_30m": "trending",
    "05_reversal_long_1H": "neutral",
    "06_reversal_short_1H": "trending",
    "07_reversal_long_4H": "neutral",
    "08_reversal_short_4H": "trending",
    "09_reversal_long_6Hutc": "neutral",
    "10_reversal_short_6Hutc": "neutral",
    "11_parity_long_15m": "neutral",
    "12_parity_short_15m": "neutral",
    "13_parity_long_30m": "ranging",
    "14_parity_short_30m": "trending",
    "15_parity_long_1H": "neutral",
    "16_parity_short_1H": "trending",
    "17_parity_long_4H": "ranging",
    "18_parity_short_4H": "neutral",
    "19_parity_long_6Hutc": "neutral",
    "20_parity_short_6Hutc": "neutral",
    "21_flag_long_15m": "neutral",
    "22_flag_short_15m": "neutral",
    "23_flag_long_30m": "neutral",
    "24_flag_short_30m": "neutral",
    "25_flag_long_1H": "neutral",
    "26_flag_short_1H": "neutral",
    "27_flag_long_4H": "ranging",
    "28_flag_short_4H": "neutral",
    "29_flag_long_6Hutc": "ranging",
    "30_flag_short_6Hutc": "trending",
    "31_orderblocks_long_15m": "neutral",
    "32_orderblocks_short_15m": "neutral",
    "33_orderblocks_long_30m": "neutral",
    "34_orderblocks_short_30m": "neutral",
    "35_orderblocks_long_1H": "neutral",
    "36_orderblocks_short_1H": "trending",
    "37_orderblocks_long_4H": "ranging",
    "38_orderblocks_short_4H": "neutral",
    "39_orderblocks_long_6Hutc": "ranging",
    "40_orderblocks_short_6Hutc": "neutral",
}
