"""
Trading Strategies Configuration

Auto-generated by BOT_batch. Do not edit manually.
Copy to BOT_trading/config/strategies_NN.py to deploy.
"""

STRATEGIES = [
    {
        "id": "18_flag_long_1H",
        "name": "flag_long_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "long",
        "regime_trending_uptrend": 1,
        "regime_trending_dwtrend": 0,
        "regime_ranging_uptrend": 1,
        "regime_ranging_dwtrend": 0,
        "regime_volatile_uptrend": 1,
        "regime_volatile_dwtrend": 0,
        "sell_after_ncandles": 50,
        "order_amount": 160,
        "impulse": 2,
        "flag": 30,
        "ma_period": 10,
        "lookback": 40,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "20_flag_short_1H",
        "name": "flag_short_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0,
        "regime_trending_dwtrend": 1,
        "regime_ranging_uptrend": 0,
        "regime_ranging_dwtrend": 1,
        "regime_volatile_uptrend": 0,
        "regime_volatile_dwtrend": 0,
        "sell_after_ncandles": 100,
        "order_amount": 160,
        "impulse": 2,
        "flag": 10,
        "ma_period": 10,
        "lookback": 20,
        "tp_pct": 2,
        "sl_pct": 3,
    },
]
