"""
Trading Strategies Configuration

Auto-generated by BOT_batch. Do not edit manually.
Copy to BOT_trading/config/strategies_NN.py to deploy.
"""

STRATEGIES = [
    {
        "id": "04_reversal_short_4H",
        "name": "reversal_short_4H",
        "timeframe": "4H",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0,
        "regime_trending_dwtrend": 1,
        "regime_ranging_uptrend": 0,
        "regime_ranging_dwtrend": 1,
        "regime_volatile_uptrend": 0,
        "regime_volatile_dwtrend": 1,
        "sell_after_ncandles": 50,
        "order_amount": 80,
        "lookback": 3,
        "tolerance": 30,
        "ma_period": 10,
        "tp_pct": 4,
        "sl_pct": 3,
    },
]
