"""
strategies_BT_E1_batch.py — Input for BOT_batch. Do not edit manually.
Generated from strategies_E1.py. Re-run this script after each production deploy.
"""

STRATEGIES = [
    {
        "id": "02_reversal_long_4H",
        "name": "reversal_long_4H",
        "timeframe": "4H",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 2,
        "tolerance": 30,
        "ma_period": 25,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "03_parity_long_4H",
        "name": "parity_long_4H",
        "timeframe": "4H",
        "active": True,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 150,
        "tolerance": 30,
        "ma_period": 10,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "04_reversal_short_4H",
        "name": "reversal_short_4H",
        "timeframe": "4H",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 3,
        "tolerance": 30,
        "ma_period": 10,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "06_reversal_long_1H",
        "name": "reversal_long_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 280,
        "lookback": 6,
        "tolerance": 25,
        "ma_period": 10,
        "tp_pct": 3,
        "sl_pct": 3,
    },
    {
        "id": "07_reversal_short_1H",
        "name": "reversal_short_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 280,
        "lookback": 4,
        "tolerance": 15,
        "ma_period": 10,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "08_reversal_long_6Hutc",
        "name": "reversal_long_6Hutc",
        "timeframe": "6Hutc",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 2,
        "tolerance": 5,
        "ma_period": 25,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "09_reversal_short_6Hutc",
        "name": "reversal_short_6Hutc",
        "timeframe": "6Hutc",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 3,
        "tolerance": 60,
        "ma_period": 10,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "10_parity_long_1H",
        "name": "parity_long_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 280,
        "lookback": 150,
        "tolerance": 10,
        "ma_period": 10,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "11_parity_short_1H",
        "name": "parity_short_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 100,
        "tolerance": 10,
        "ma_period": 10,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "12_parity_long_6Hutc",
        "name": "parity_long_6Hutc",
        "timeframe": "6Hutc",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 50,
        "tolerance": 10,
        "ma_period": 10,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "13_orderblocks_short_4H",
        "name": "orderblocks_short_4H",
        "timeframe": "4H",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 50,
        "tolerance": 45,
        "impulse": 0.02,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "17_flag_long_4H",
        "name": "flag_long_4H",
        "timeframe": "4H",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 12,
        "ma_period": 10,
        "impulse": 3,
        "flag": 10,
        "tp_pct": 3,
        "sl_pct": 3,
    },
    {
        "id": "18_flag_long_1H",
        "name": "flag_long_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 60,
        "ma_period": 10,
        "impulse": 2,
        "flag": 30,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "19_flag_short_4H",
        "name": "flag_short_4H",
        "timeframe": "4H",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 8,
        "ma_period": 10,
        "impulse": 1,
        "flag": 30,
        "tp_pct": 3,
        "sl_pct": 3,
    },
    {
        "id": "20_flag_short_1H",
        "name": "flag_short_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 280,
        "lookback": 20,
        "ma_period": 10,
        "impulse": 2,
        "flag": 20,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "21_parity_short_4H",
        "name": "parity_short_4H",
        "timeframe": "4H",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 100,
        "tolerance": 40,
        "ma_period": 10,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "22_parity_short_6Hutc",
        "name": "parity_short_6Hutc",
        "timeframe": "6Hutc",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 100,
        "tolerance": 30,
        "ma_period": 10,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "24_flag_long_6Hutc",
        "name": "flag_long_6Hutc",
        "timeframe": "6Hutc",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 60,
        "ma_period": 10,
        "impulse": 2,
        "flag": 20,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "25_flag_short_6Hutc",
        "name": "flag_short_6Hutc",
        "timeframe": "6Hutc",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 40,
        "ma_period": 10,
        "impulse": 3,
        "flag": 40,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "26_orderblocks_long_4H",
        "name": "orderblocks_long_4H",
        "timeframe": "4H",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 280,
        "lookback": 150,
        "tolerance": 25,
        "impulse": 0.02,
        "tp_pct": 4,
        "sl_pct": 3,
    },
    {
        "id": "27_orderblocks_short_1H",
        "name": "orderblocks_short_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 280,
        "lookback": 75,
        "tolerance": 25,
        "impulse": 0.05,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "28_orderblocks_long_1H",
        "name": "orderblocks_long_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 280,
        "lookback": 50,
        "tolerance": 45,
        "impulse": 0.02,
        "tp_pct": 3,
        "sl_pct": 3,
    },
]
