"""
Montecarlo OOS reference values for drift detection.
P5_WINRATE: Percentile 5 (floor - worst acceptable performance)
P50_WINRATE: Percentile 50 (median - expected performance)
Auto-generated by BOT_batch on 2026-05-13 10:29. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '02_reversal_long_4H': {
        'p5_winrate':  37.5,
        'p50_winrate': 46.1,
    },
    '03_parity_long_4H': {
        'p5_winrate':  45.3,
        'p50_winrate': 53.6,
    },
    '04_reversal_short_4H': {
        'p5_winrate':  43.4,
        'p50_winrate': 51.7,
    },
    '06_reversal_long_1H': {
        'p5_winrate':  47.5,
        'p50_winrate': 53.9,
    },
    '07_reversal_short_1H': {
        'p5_winrate':  64.8,
        'p50_winrate': 69.6,
    },
    '10_parity_long_1H': {
        'p5_winrate':  44.8,
        'p50_winrate': 51.8,
    },
    '11_parity_short_1H': {
        'p5_winrate':  64.1,
        'p50_winrate': 68.9,
    },
    '13_orderblocks_short_4H': {
        'p5_winrate':  39.7,
        'p50_winrate': 49.5,
    },
    '17_flag_long_4H': {
        'p5_winrate':  46.1,
        'p50_winrate': 54.9,
    },
    '18_flag_long_1H': {
        'p5_winrate':  57.4,
        'p50_winrate': 63.7,
    },
    '19_flag_short_4H': {
        'p5_winrate':  52.0,
        'p50_winrate': 59.4,
    },
    '20_flag_short_1H': {
        'p5_winrate':  65.2,
        'p50_winrate': 70.2,
    },
    '26_orderblocks_long_4H': {
        'p5_winrate':  35.7,
        'p50_winrate': 44.1,
    },
    '27_orderblocks_short_1H': {
        'p5_winrate':  63.1,
        'p50_winrate': 68.2,
    },
    '28_orderblocks_long_1H': {
        'p5_winrate':  38.8,
        'p50_winrate': 45.4,
    },
}
