"""
strategies_loop.py — Batch loop configuration.
Edit param_grid, n_symbols and order_amount before each run.
This file is NOT updated by the batch automatically.
"""

STRATEGIES_LOOP = [
    {
        "id": "02_reversal_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [2],
            "TOLERANCE": [50],
            "MA_PERIOD": [10],
            "TP_PCT": [4],
            "SL_PCT": [3],
        },
    },
    {
        "id": "03_parity_long_4H",
        "n_symbols": 20,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [100],
            "TOLERANCE": [20],
            "MA_PERIOD": [10],
            "TP_PCT": [4],
            "SL_PCT": [3],
        },
    },
    {
        "id": "04_reversal_short_4H",
        "n_symbols": 30,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [3],
            "TOLERANCE": [20],
            "MA_PERIOD": [10],
            "TP_PCT": [3],
            "SL_PCT": [3],
        },
    },
    {
        "id": "06_reversal_long_1H",
        "n_symbols": 8,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [100],
            "LOOKBACK": [8],
            "TOLERANCE": [25],
            "MA_PERIOD": [10],
            "TP_PCT": [4],
            "SL_PCT": [3],
        },
    },
    {
        "id": "07_reversal_short_1H",
        "n_symbols": 8,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [100],
            "LOOKBACK": [5],
            "TOLERANCE": [5],
            "MA_PERIOD": [25],
            "TP_PCT": [2],
            "SL_PCT": [4],
        },
    },
    {
        "id": "08_reversal_long_6Hutc",
        "n_symbols": 8,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [2],
            "TOLERANCE": [5],
            "MA_PERIOD": [10],
            "TP_PCT": [4],
            "SL_PCT": [3],
        },
    },
    {
        "id": "09_reversal_short_6Hutc",
        "n_symbols": 30,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [3],
            "TOLERANCE": [60],
            "MA_PERIOD": [10],
            "TP_PCT": [4],
            "SL_PCT": [3],
        },
    },
    {
        "id": "10_parity_long_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [75],
            "LOOKBACK": [150],
            "TOLERANCE": [5],
            "MA_PERIOD": [10],
            "TP_PCT": [2],
            "SL_PCT": [4],
        },
    },
    {
        "id": "11_parity_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [100],
            "TOLERANCE": [2],
            "MA_PERIOD": [10],
            "TP_PCT": [2],
            "SL_PCT": [3],
        },
    },
    {
        "id": "12_parity_long_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [10],
            "TOLERANCE": [10],
            "MA_PERIOD": [10],
            "TP_PCT": [4],
            "SL_PCT": [3],
        },
    },
    {
        "id": "13_orderblocks_short_4H",
        "n_symbols": 30,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [150],
            "TOLERANCE": [35],
            "IMPULSE": [0.02],
            "TP_PCT": [4],
            "SL_PCT": [3],
        },
    },
    {
        "id": "17_flag_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [40],
            "MA_PERIOD": [10],
            "IMPULSE": [4],
            "FLAG": [20],
            "TP_PCT": [3],
            "SL_PCT": [3],
        },
    },
    {
        "id": "19_flag_short_4H",
        "n_symbols": 20,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [10],
            "MA_PERIOD": [10],
            "IMPULSE": [2],
            "FLAG": [50],
            "TP_PCT": [3],
            "SL_PCT": [4],
        },
    },
    {
        "id": "20_flag_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [50],
            "LOOKBACK": [60],
            "MA_PERIOD": [25],
            "IMPULSE": [2],
            "FLAG": [10],
            "TP_PCT": [2],
            "SL_PCT": [3],
        },
    },
]
