# Auto-generated by regime_GE.py
# ATR_NORM(10)>=0.04 | ER(10)>=0.6 | MODE=OR
# Classification: ranging=block_trending | trending=block_ranging | both | neutral

ATR_NORM_WINDOW    = 10
ATR_NORM_THRESHOLD = 0.04
ER_WINDOW    = 10
ER_THRESHOLD = 0.6
COMBINE_MODE = 'OR'

REGIME_BINS = {
    "01_reversal_long_15m": "neutral",
    "02_reversal_short_15m": "neutral",
    "03_reversal_long_30m": "neutral",
    "04_reversal_short_30m": "neutral",
    "05_reversal_long_1H": "neutral",
    "06_reversal_short_1H": "neutral",
    "07_reversal_long_4H": "neutral",
    "08_reversal_short_4H": "neutral",
    "09_reversal_long_6Hutc": "neutral",
    "10_reversal_short_6Hutc": "neutral",
    "11_parity_long_15m": "neutral",
    "12_parity_short_15m": "neutral",
    "13_parity_long_30m": "neutral",
    "14_parity_short_30m": "neutral",
    "15_parity_long_1H": "neutral",
    "16_parity_short_1H": "neutral",
    "17_parity_long_4H": "neutral",
    "18_parity_short_4H": "neutral",
    "19_parity_long_6Hutc": "neutral",
    "20_parity_short_6Hutc": "neutral",
    "21_flag_long_15m": "neutral",
    "22_flag_short_15m": "neutral",
    "23_flag_long_30m": "neutral",
    "24_flag_short_30m": "neutral",
    "25_flag_long_1H": "neutral",
    "26_flag_short_1H": "neutral",
    "27_flag_long_4H": "neutral",
    "28_flag_short_4H": "neutral",
    "29_flag_long_6Hutc": "neutral",
    "30_flag_short_6Hutc": "neutral",
    "31_orderblocks_long_15m": "neutral",
    "32_orderblocks_short_15m": "neutral",
    "33_orderblocks_long_30m": "neutral",
    "34_orderblocks_short_30m": "neutral",
    "35_orderblocks_long_1H": "neutral",
    "36_orderblocks_short_1H": "neutral",
    "37_orderblocks_long_4H": "neutral",
    "38_orderblocks_short_4H": "neutral",
    "39_orderblocks_long_6Hutc": "neutral",
    "40_orderblocks_short_6Hutc": "neutral",
}
