#shared/transfers/generator_dict_strategies.py
import os
import sys
from importlib import import_module
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "BOT_trading")))
from datetime import datetime

# =============================================================================
# CONFIGURATION
# =============================================================================
STRATEGIES_SET_NAME = "00"
TARGET_BATCH        = f"BOT_batch_{STRATEGIES_SET_NAME}"

PROD_STRATEGIES    = import_module(f"config.strategies_{STRATEGIES_SET_NAME}").STRATEGIES
OUTPUT_BATCH       = os.path.join(os.path.dirname(__file__), "..", TARGET_BATCH, "strategies_files", f"strategies_BT_{STRATEGIES_SET_NAME}_batch.py")
OUTPUT_LOOP        = os.path.join(os.path.dirname(__file__), "..", TARGET_BATCH, "strategies_files", f"strategies_loop_{STRATEGIES_SET_NAME}.py")
OUTPUT_REGIME_BINS = os.path.join(os.path.dirname(__file__), "..", TARGET_BATCH, "strategies_files", f"regime_bins_{STRATEGIES_SET_NAME}.py")
PARAM_GRID_KEYS    = {"lookback", "tolerance", "ma_period", "tp_pct", "sl_pct", "impulse", "flag"}
SIGNAL_PARAM_KEYS  = ("lookback", "tolerance", "ma_period", "impulse", "flag")
REGIME_BIN_KEYS    = (
    "regime_uptrend",
    "regime_dwtrend",
    "regime_neutral",
)

symbols_live_folder     = os.path.join(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")), "BOT_trading", "symbols_live", STRATEGIES_SET_NAME)
DEFAULT_N_SYMBOLS       = 10
DEFAULT_ORDER_AMOUNT    = 100
USE_SYMBOLS_LIVE_FOR_N  = True
USE_GLOBAL_VARS_IN_LOOP = True   # True: generate N_SYMBOLS/ORDER_AMOUNT as global vars; False: inline values


# =============================================================================
# HELPERS
# =============================================================================
def _fmt_val(val):
    if isinstance(val, bool):
        return str(val)
    if isinstance(val, str):
        return f'"{val}"'
    return str(val)


def _write(path, lines):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def _write_init(folder):
    init_path = os.path.join(folder, "__init__.py")
    if not os.path.exists(init_path):
        open(init_path, "w").close()


# =============================================================================
# GENERATE strategies_BT_{SET}_batch.py
# =============================================================================
def generate_batch():
    lines = [
        '"""',
        f'strategies_BT_{STRATEGIES_SET_NAME}_batch.py — Input for BOT_batch. Do not edit manually.',
        f'Generated from strategies_{STRATEGIES_SET_NAME}.py. Re-run this script after each production deploy.',
        f'Auto-generated by ACCOUNT_files_generator on {datetime.now().strftime("%Y-%m-%d %H:%M")}.',
        '"""',
        '',
        'STRATEGIES = [',
    ]

    for s in PROD_STRATEGIES:
        lines.append("    {")
        lines.append(f'        "id": "{s["id"]}",')
        lines.append(f'        "name": "{s["name"]}",')
        lines.append(f'        "timeframe": "{s["timeframe"]}",')
        lines.append(f'        "active": {s.get("active", False)},')
        lines.append(f'        "direction": "{s["direction"]}",')
        for bin_key in REGIME_BIN_KEYS:
            lines.append(f'        "{bin_key}": {float(s.get(bin_key, 1.0))},')
        lines.append(f'        "sell_after_ncandles": {s.get("sell_after_ncandles", 0)},')
        lines.append(f'        "order_amount_prod": {s.get("order_amount", 200)},')
        for k in SIGNAL_PARAM_KEYS:
            if k in s:
                lines.append(f'        "{k}": {_fmt_val(s[k])},')
        for k in ("tp_pct", "sl_pct"):
            if k in s:
                lines.append(f'        "{k}": {_fmt_val(s[k])},')
        lines.append("    },")

    lines.append("]")
    _write(OUTPUT_BATCH, lines)
    _write_init(os.path.dirname(os.path.abspath(OUTPUT_BATCH)))
    print(f"✅ strategies_BT_{STRATEGIES_SET_NAME}_batch.py generated → {os.path.abspath(OUTPUT_BATCH)}")


# =============================================================================
# GENERATE strategies_loop_{SET}.py
# =============================================================================
def generate_loop():
    lines = [
        '"""',
        f'strategies_loop_{STRATEGIES_SET_NAME}.py — Batch loop configuration.',
        'Edit param_grid, N_SYMBOLS and ORDER_AMOUNT before each run.',
        'This file is NOT updated by the batch automatically.',
        f'Auto-generated by ACCOUNT_files_generator on {datetime.now().strftime("%Y-%m-%d %H:%M")}.',
        '"""',
        '',
    ]

    if USE_GLOBAL_VARS_IN_LOOP:
        lines += [
            f'N_SYMBOLS    = {DEFAULT_N_SYMBOLS}',
            f'ORDER_AMOUNT = {DEFAULT_ORDER_AMOUNT}',
            '',
        ]

    lines.append('STRATEGIES_LOOP = [')

    for s in PROD_STRATEGIES:
        live_path = os.path.join(symbols_live_folder, f"symbols_live_{s['id']}_{s['timeframe']}.csv")
        if USE_SYMBOLS_LIVE_FOR_N and os.path.exists(live_path):
            import pandas as pd
            n_symbols = len(pd.read_csv(live_path, header=None))
        else:
            n_symbols = DEFAULT_N_SYMBOLS

        n_symbols_val    = "N_SYMBOLS"    if USE_GLOBAL_VARS_IN_LOOP else n_symbols
        order_amount_val = "ORDER_AMOUNT" if USE_GLOBAL_VARS_IN_LOOP else DEFAULT_ORDER_AMOUNT

        param_grid = {"SELL_AFTER": [s.get("sell_after_ncandles", 0)]}
        for k in SIGNAL_PARAM_KEYS:
            if k in s:
                param_grid[k.upper()] = [s[k]]
        for k in ("tp_pct", "sl_pct"):
            if k in s:
                param_grid[k.upper()] = [s[k]]

        lines.append("    {")
        lines.append(f'        "id": "{s["id"]}",')
        lines.append(f'        "N_SYMBOLS": {n_symbols_val},')
        lines.append(f'        "ORDER_AMOUNT": {order_amount_val},')
        lines.append(f'        "param_grid": {{')
        for pk, pv in param_grid.items():
            lines.append(f'            "{pk}": {pv},')
        lines.append(f'        }},')
        lines.append("    },")

    lines.append("]")
    _write(OUTPUT_LOOP, lines)
    print(f"✅ strategies_loop_{STRATEGIES_SET_NAME}.py generated → {os.path.abspath(OUTPUT_LOOP)}")

# =============================================================================
# GENERATE regime_bins_{SET}.py
# =============================================================================
def generate_regime_bins():
    from config.settings import ACCOUNTS
    account_cfg = ACCOUNTS.get(STRATEGIES_SET_NAME, {})
    ma_window   = account_cfg.get("regime_ma_window", "?")

    lines = [
        '"""',
        f'regime_bins_{STRATEGIES_SET_NAME}.py — Regime bin assignment per strategy.',
        f'Generated from strategies_{STRATEGIES_SET_NAME}.py. Re-run this script after each production deploy.',
        f'Auto-generated by ACCOUNT_files_generator on {datetime.now().strftime("%Y-%m-%d %H:%M")}.',
        '"""',
        '',
        f"INDICATOR_CFG = {{'ma_window': {ma_window}}}",
        '',
        'REGIME_BINS = {',
    ]

    for s in PROD_STRATEGIES:
        active_bins = [
            k.replace("regime_", "") for k in REGIME_BIN_KEYS
            if s.get(k, 0) == 1 and k != "regime_neutral"
        ]
        lines.append(f'    "{s["id"]}": {active_bins},')

    lines.append("}")
    _write(OUTPUT_REGIME_BINS, lines)
    _write_init(os.path.dirname(os.path.abspath(OUTPUT_REGIME_BINS)))
    print(f"✅ regime_bins_{STRATEGIES_SET_NAME}.py generated → {os.path.abspath(OUTPUT_REGIME_BINS)}")

# =============================================================================
# MAIN
# =============================================================================
if __name__ == "__main__":
    generate_batch()
    generate_loop()
    generate_regime_bins()
    print(f"   Strategies: {len(PROD_STRATEGIES)}")