"""
Regime OOS1 reference values for drift detection.
P_TARGET_WINRATE: Observed winrate on regime-filtered OOS1 trades (used as binomial p_target)
Auto-generated by BOT_batch on 2026-05-13 21:18. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '30_reversal_long_1H': {
        'p_target_winrate': 69.7,
    },
    '31_reversal_long_30m': {
        'p_target_winrate': 68.1,
    },
    '32_reversal_long_15m': {
        'p_target_winrate': 59.6,
    },
    '33_reversal_short_1H': {
        'p_target_winrate': 66.7,
    },
    '34_reversal_short_30m': {
        'p_target_winrate': 68.5,
    },
    '35_reversal_short_15m': {
        'p_target_winrate': 55.5,
    },
    '36_parity_long_1H': {
        'p_target_winrate': 61.4,
    },
    '37_parity_long_30m': {
        'p_target_winrate': 57.5,
    },
    '38_parity_long_15m': {
        'p_target_winrate': 58.7,
    },
    '39_parity_short_1H': {
        'p_target_winrate': 68.8,
    },
    '40_parity_short_30m': {
        'p_target_winrate': 67.1,
    },
    '41_parity_short_15m': {
        'p_target_winrate': 52.0,
    },
    '42_flag_long_1H': {
        'p_target_winrate': 68.6,
    },
    '43_flag_long_30m': {
        'p_target_winrate': 66.7,
    },
    '44_flag_long_15m': {
        'p_target_winrate': 71.4,
    },
    '45_flag_short_1H': {
        'p_target_winrate': 66.7,
    },
    '46_flag_short_30m': {
        'p_target_winrate': 66.0,
    },
    '47_flag_short_15m': {
        'p_target_winrate': 60.0,
    },
    '48_orderblocks_long_1H': {
        'p_target_winrate': 74.8,
    },
    '49_orderblocks_long_30m': {
        'p_target_winrate': 63.3,
    },
    '50_orderblocks_long_15m': {
        'p_target_winrate': 63.7,
    },
    '51_orderblocks_short_1H': {
        'p_target_winrate': 61.4,
    },
    '52_orderblocks_short_30m': {
        'p_target_winrate': 69.6,
    },
    '53_orderblocks_short_15m': {
        'p_target_winrate': 56.5,
    },
}
