# Auto-generated by bin_session.py
# Sessions (UTC): asian_early=00-04h, asian_late=04-08h, european_early=08-12h, european_late=12-16h, american_early=16-20h, american_late=20-24h
# Train: IS + OOS2 + OOS3
# Match mode: intersection

SESSIONS = {'asian_early': (0, 4), 'asian_late': (4, 8), 'european_early': (8, 12), 'european_late': (12, 16), 'american_early': (16, 20), 'american_late': (20, 24)}

REGIME_BINS = {
    "01_reversal_long_15m": {},
    "02_reversal_short_15m": {},
    "03_reversal_long_30m": {},
    "04_reversal_short_30m": {},
    "05_reversal_long_1H": {},
    "06_reversal_short_1H": {},
    "07_reversal_long_4H": {},
    "08_reversal_short_4H": {},
    "09_reversal_long_6Hutc": {},
    "10_reversal_short_6Hutc": {},
    "11_parity_long_15m": {},
    "12_parity_short_15m": {},
    "13_parity_long_30m": {},
    "14_parity_short_30m": {},
    "15_parity_long_1H": {},
    "16_parity_short_1H": {},
    "17_parity_long_4H": {},
    "18_parity_short_4H": {},
    "19_parity_long_6Hutc": {},
    "20_parity_short_6Hutc": {},
    "21_flag_long_15m": {"european_early"},
    "22_flag_short_15m": {},
    "23_flag_long_30m": {},
    "24_flag_short_30m": {},
    "25_flag_long_1H": {},
    "26_flag_short_1H": {},
    "27_flag_long_4H": {},
    "28_flag_short_4H": {},
    "29_flag_long_6Hutc": {},
    "30_flag_short_6Hutc": {},
    "31_orderblocks_long_15m": {},
    "32_orderblocks_short_15m": {},
    "33_orderblocks_long_30m": {},
    "34_orderblocks_short_30m": {},
    "35_orderblocks_long_1H": {},
    "36_orderblocks_short_1H": {},
    "37_orderblocks_long_4H": {},
    "38_orderblocks_short_4H": {},
    "39_orderblocks_long_6Hutc": {},
    "40_orderblocks_short_6Hutc": {},
}
