# Auto-generated by bin_volume.py
# Vol window: 20 bars | Low<0.8x | High>1.5x mean
# Train: IS + OOS2 + OOS3
# Match mode: exact | min_periods=2

VOL_WINDOW  = 20
VOL_LOW_TH  = 0.8
VOL_HIGH_TH = 1.5

REGIME_BINS = {
    "01_reversal_long_15m": {},
    "02_reversal_short_15m": {},
    "03_reversal_long_30m": {"vol_high"},
    "04_reversal_short_30m": {},
    "05_reversal_long_1H": {},
    "06_reversal_short_1H": {},
    "07_reversal_long_4H": {},
    "08_reversal_short_4H": {"vol_high"},
    "09_reversal_long_6Hutc": {"vol_low"},
    "10_reversal_short_6Hutc": {},
    "11_parity_long_15m": {"vol_normal"},
    "12_parity_short_15m": {},
    "13_parity_long_30m": {},
    "14_parity_short_30m": {},
    "15_parity_long_1H": {},
    "16_parity_short_1H": {},
    "17_parity_long_4H": {"vol_low"},
    "18_parity_short_4H": {"vol_high"},
    "19_parity_long_6Hutc": {},
    "20_parity_short_6Hutc": {},
    "21_flag_long_15m": {},
    "22_flag_short_15m": {},
    "23_flag_long_30m": {"vol_normal"},
    "24_flag_short_30m": {},
    "25_flag_long_1H": {"vol_normal"},
    "26_flag_short_1H": {},
    "27_flag_long_4H": {"vol_low"},
    "28_flag_short_4H": {},
    "29_flag_long_6Hutc": {},
    "30_flag_short_6Hutc": {},
    "31_orderblocks_long_15m": {},
    "32_orderblocks_short_15m": {},
    "33_orderblocks_long_30m": {},
    "34_orderblocks_short_30m": {},
    "35_orderblocks_long_1H": {},
    "36_orderblocks_short_1H": {},
    "37_orderblocks_long_4H": {},
    "38_orderblocks_short_4H": {},
    "39_orderblocks_long_6Hutc": {},
    "40_orderblocks_short_6Hutc": {},
}
