"""
Regime OOS1 reference values for drift detection.
P_TARGET_WINRATE: Observed winrate on regime-filtered OOS1 trades (used as binomial p_target)
Auto-generated by BOT_batch on 2026-05-17 16:34. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '02_reversal_long_4H': {
        'p_target_winrate': 55.9,
    },
    '03_parity_long_4H': {
        'p_target_winrate': 64.8,
    },
    '04_reversal_short_4H': {
        'p_target_winrate': 60.2,
    },
    '06_reversal_long_1H': {
        'p_target_winrate': 68.1,
    },
    '07_reversal_short_1H': {
        'p_target_winrate': 79.6,
    },
    '08_reversal_long_6Hutc': {
        'p_target_winrate': 54.1,
    },
    '09_reversal_short_6Hutc': {
        'p_target_winrate': 61.2,
    },
    '10_parity_long_1H': {
        'p_target_winrate': 72.2,
    },
    '11_parity_short_1H': {
        'p_target_winrate': 79.6,
    },
    '12_parity_long_6Hutc': {
        'p_target_winrate': 55.2,
    },
    '13_orderblocks_short_4H': {
        'p_target_winrate': 64.4,
    },
    '17_flag_long_4H': {
        'p_target_winrate': 64.3,
    },
    '18_flag_long_1H': {
        'p_target_winrate': 76.8,
    },
    '19_flag_short_4H': {
        'p_target_winrate': 72.2,
    },
    '20_flag_short_1H': {
        'p_target_winrate': 79.3,
    },
    '21_parity_short_4H': {
        'p_target_winrate': 61.0,
    },
    '22_parity_short_6Hutc': {
        'p_target_winrate': 60.7,
    },
    '24_flag_long_6Hutc': {
        'p_target_winrate': 54.3,
    },
    '25_flag_short_6Hutc': {
        'p_target_winrate': 68.4,
    },
    '26_orderblocks_long_4H': {
        'p_target_winrate': 54.8,
    },
    '27_orderblocks_short_1H': {
        'p_target_winrate': 77.5,
    },
    '28_orderblocks_long_1H': {
        'p_target_winrate': 58.6,
    },
}
