"""
Regime OOS1 reference values for drift detection.
P_TARGET_WINRATE: Observed winrate on OOS1 trades (used as binomial p_target)
Auto-generated by BOT_batch on 2026-05-18 12:05. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '30_reversal_long_30m': {
        'p_target_winrate': 67.7,
    },
    '31_reversal_long_15m': {
        'p_target_winrate': 59.3,
    },
    '32_reversal_short_30m': {
        'p_target_winrate': 76.0,
    },
    '33_reversal_short_15m': {
        'p_target_winrate': 58.7,
    },
    '34_parity_long_30m': {
        'p_target_winrate': 55.2,
    },
    '35_parity_long_15m': {
        'p_target_winrate': 57.5,
    },
    '36_parity_short_30m': {
        'p_target_winrate': 67.1,
    },
    '37_parity_short_15m': {
        'p_target_winrate': 53.0,
    },
    '38_flag_long_30m': {
        'p_target_winrate': 64.1,
    },
    '39_flag_long_15m': {
        'p_target_winrate': 54.2,
    },
    '40_flag_short_30m': {
        'p_target_winrate': 67.8,
    },
    '41_flag_short_15m': {
        'p_target_winrate': 71.4,
    },
    '42_orderblocks_long_30m': {
        'p_target_winrate': 66.9,
    },
    '43_orderblocks_long_15m': {
        'p_target_winrate': 64.6,
    },
    '44_orderblocks_short_30m': {
        'p_target_winrate': 70.7,
    },
    '45_orderblocks_short_15m': {
        'p_target_winrate': 57.7,
    },
}
