"""
Regime OOS1 reference values for drift detection.
P_TARGET_WINRATE: Observed winrate on regime-filtered OOS1 trades (used as binomial p_target)
Auto-generated by BOT_batch on 2026-05-14 10:05. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '02_reversal_long_4H': {
        'p_target_winrate': 56.2,
    },
    '03_parity_long_4H': {
        'p_target_winrate': 64.0,
    },
    '04_reversal_short_4H': {
        'p_target_winrate': 60.1,
    },
    '06_reversal_long_1H': {
        'p_target_winrate': 68.2,
    },
    '07_reversal_short_1H': {
        'p_target_winrate': 79.8,
    },
    '08_reversal_long_6Hutc': {
        'p_target_winrate': 51.4,
    },
    '09_reversal_short_6Hutc': {
        'p_target_winrate': 59.2,
    },
    '10_parity_long_1H': {
        'p_target_winrate': 68.1,
    },
    '11_parity_short_1H': {
        'p_target_winrate': 79.9,
    },
    '12_parity_long_6Hutc': {
        'p_target_winrate': 56.5,
    },
    '13_orderblocks_short_4H': {
        'p_target_winrate': 64.3,
    },
    '17_flag_long_4H': {
        'p_target_winrate': 66.4,
    },
    '18_flag_long_1H': {
        'p_target_winrate': 77.2,
    },
    '19_flag_short_4H': {
        'p_target_winrate': 69.7,
    },
    '20_flag_short_1H': {
        'p_target_winrate': 79.6,
    },
    '21_parity_short_4H': {
        'p_target_winrate': 60.7,
    },
    '22_parity_short_6Hutc': {
        'p_target_winrate': 61.5,
    },
    '24_flag_long_6Hutc': {
        'p_target_winrate': 54.7,
    },
    '25_flag_short_6Hutc': {
        'p_target_winrate': 68.0,
    },
    '26_orderblocks_long_4H': {
        'p_target_winrate': 59.8,
    },
    '27_orderblocks_short_1H': {
        'p_target_winrate': 77.3,
    },
    '28_orderblocks_long_1H': {
        'p_target_winrate': 58.4,
    },
}
