"""
strategies_loop_00_01_rwa.py — Batch loop configuration for RWA.
Edit param_grid, n_symbols and order_amount before each run.
This file is NOT updated by the batch automatically.
"""

STRATEGIES_LOOP = [
    # =========================================================================
    # REVERSAL
    # =========================================================================
    {
        "id": "01_reversal_long_15m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [6],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "02_reversal_short_15m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [6],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "03_reversal_long_30m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [6],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "04_reversal_short_30m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [6],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "05_reversal_long_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [6],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "06_reversal_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [6],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "07_reversal_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [6],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "08_reversal_short_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [6],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "09_reversal_long_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [6],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "10_reversal_short_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [6],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    # =========================================================================
    # PARITY
    # =========================================================================
    {
        "id": "11_parity_long_15m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "12_parity_short_15m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "13_parity_long_30m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "14_parity_short_30m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "15_parity_long_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "16_parity_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "17_parity_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "18_parity_short_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "19_parity_long_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "20_parity_short_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "MA_PERIOD": [10, 25],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    # =========================================================================
    # FLAG
    # =========================================================================
    {
        "id": "21_flag_long_15m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20, 40],
            "MA_PERIOD": [10, 25],
            "IMPULSE": [2, 4],
            "FLAG": [10, 20, 30],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "22_flag_short_15m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20, 40],
            "MA_PERIOD": [10, 25],
            "IMPULSE": [2, 4],
            "FLAG": [10, 20, 30],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "23_flag_long_30m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20, 40],
            "MA_PERIOD": [10, 25],
            "IMPULSE": [2, 4],
            "FLAG": [10, 20, 30],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "24_flag_short_30m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20, 40],
            "MA_PERIOD": [10, 25],
            "IMPULSE": [2, 4],
            "FLAG": [10, 20, 30],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "25_flag_long_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20, 40],
            "MA_PERIOD": [10, 25],
            "IMPULSE": [2, 4],
            "FLAG": [10, 20, 30],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "26_flag_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20, 40],
            "MA_PERIOD": [10, 25],
            "IMPULSE": [2, 4],
            "FLAG": [10, 20, 30],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "27_flag_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20, 40],
            "MA_PERIOD": [10, 25],
            "IMPULSE": [2, 4],
            "FLAG": [10, 20, 30],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "28_flag_short_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20, 40],
            "MA_PERIOD": [10, 25],
            "IMPULSE": [2, 4],
            "FLAG": [10, 20, 30],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "29_flag_long_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20, 40],
            "MA_PERIOD": [10, 25],
            "IMPULSE": [2, 4],
            "FLAG": [10, 20, 30],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "30_flag_short_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [20, 40],
            "MA_PERIOD": [10, 25],
            "IMPULSE": [2, 4],
            "FLAG": [10, 20, 30],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    # =========================================================================
    # ORDERBLOCKS
    # =========================================================================
    {
        "id": "31_orderblocks_long_15m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "IMPULSE": [0.02, 0.05, 0.08],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "32_orderblocks_short_15m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "IMPULSE": [0.02, 0.05, 0.08],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "33_orderblocks_long_30m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "IMPULSE": [0.02, 0.05, 0.08],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "34_orderblocks_short_30m",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "IMPULSE": [0.02, 0.05, 0.08],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "35_orderblocks_long_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "IMPULSE": [0.02, 0.05, 0.08],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "36_orderblocks_short_1H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "IMPULSE": [0.02, 0.05, 0.08],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "37_orderblocks_long_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "IMPULSE": [0.02, 0.05, 0.08],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "38_orderblocks_short_4H",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "IMPULSE": [0.02, 0.05, 0.08],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "39_orderblocks_long_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "IMPULSE": [0.02, 0.05, 0.08],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
    {
        "id": "40_orderblocks_short_6Hutc",
        "n_symbols": 10,
        "order_amount": 80,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10, 20, 30],
            "IMPULSE": [0.02, 0.05, 0.08],
            "TP_PCT": [2,3],
            "SL_PCT": [2,3],
        },
    },
]