"""
Regime OOS1 reference values for drift detection.
P_TARGET_WINRATE: Observed winrate on regime-filtered OOS1 trades (used as binomial p_target)
Auto-generated by BOT_batch on 2026-05-13 16:40. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '02_reversal_long_4H': {
        'p_target_winrate': 56.2,
    },
    '03_parity_long_4H': {
        'p_target_winrate': 64.0,
    },
    '04_reversal_short_4H': {
        'p_target_winrate': 59.5,
    },
    '06_reversal_long_1H': {
        'p_target_winrate': 68.2,
    },
    '07_reversal_short_1H': {
        'p_target_winrate': 79.8,
    },
    '10_parity_long_1H': {
        'p_target_winrate': 68.1,
    },
    '11_parity_short_1H': {
        'p_target_winrate': 79.9,
    },
    '13_orderblocks_short_4H': {
        'p_target_winrate': 57.9,
    },
    '17_flag_long_4H': {
        'p_target_winrate': 66.4,
    },
    '18_flag_long_1H': {
        'p_target_winrate': 77.2,
    },
    '19_flag_short_4H': {
        'p_target_winrate': 70.0,
    },
    '20_flag_short_1H': {
        'p_target_winrate': 79.6,
    },
    '26_orderblocks_long_4H': {
        'p_target_winrate': 59.8,
    },
    '27_orderblocks_short_1H': {
        'p_target_winrate': 77.3,
    },
    '28_orderblocks_long_1H': {
        'p_target_winrate': 58.4,
    },
}
