"""
regime_bins_E1.py — 4-bin regime classification. Do not edit manually.
Generated by regime_GE_calibration_4bins.py
ER(40)>=0.7 | ATR_NORM(40)>=0.05
Auto-generated on 2026-06-08 09:24 UTC.
"""

ER_WINDOW             = 40
ER_THRESHOLD          = 0.7
ATR_NORM_WINDOW       = 40
ATR_NORM_THRESHOLD    = 0.05
ANALYSIS_MODE         = "SYMBOL"
REGIME_TIMEFRAME_MODE = "DAILY"

OPTIMIZE_METRIC     = "calmar"
CLASSIFICATION_MODE = "strict"
CLASSIFY_SECONDARY_METRIC = "r2"

REGIME_BINS = {
    "01_reversal_long_15m": ['ranging_highvol', 'ranging_lowvol'],
    "02_reversal_short_15m": ['ranging_highvol'],
    "03_reversal_long_30m": ['ranging_highvol'],
    "04_reversal_short_30m": ['ranging_highvol'],
    "05_reversal_long_1H": ['neutral'],
    "06_reversal_short_1H": ['neutral'],
    "07_reversal_long_4H": ['ranging_lowvol'],
    "08_reversal_short_4H": ['ranging_highvol'],
    "09_reversal_long_6Hutc": ['neutral'],  # excluded from calibration
    "10_reversal_short_6Hutc": ['neutral'],
    "11_parity_long_15m": ['neutral'],  # excluded from calibration
    "12_parity_short_15m": ['ranging_highvol'],
    "13_parity_long_30m": ['neutral'],  # excluded from calibration
    "14_parity_short_30m": ['ranging_highvol'],
    "15_parity_long_1H": ['neutral'],
    "16_parity_short_1H": ['neutral'],
    "17_parity_long_4H": ['neutral'],
    "18_parity_short_4H": ['neutral'],
    "19_parity_long_6Hutc": ['neutral'],
    "20_parity_short_6Hutc": ['neutral'],
    "21_flag_long_15m": ['ranging_highvol', 'ranging_lowvol'],
    "22_flag_short_15m": ['ranging_highvol'],
    "23_flag_long_30m": ['neutral'],
    "24_flag_short_30m": ['neutral'],
    "25_flag_long_1H": ['neutral'],
    "26_flag_short_1H": ['ranging_highvol'],
    "27_flag_long_4H": ['ranging_highvol'],
    "28_flag_short_4H": ['ranging_highvol'],
    "29_flag_long_6Hutc": ['neutral'],
    "30_flag_short_6Hutc": ['neutral'],  # excluded from calibration
    "31_orderblocks_long_15m": ['neutral'],
    "32_orderblocks_short_15m": ['ranging_highvol'],
    "33_orderblocks_long_30m": ['neutral'],
    "34_orderblocks_short_30m": ['neutral'],
    "35_orderblocks_long_1H": ['neutral'],
    "36_orderblocks_short_1H": ['neutral'],
    "37_orderblocks_long_4H": ['neutral'],
    "38_orderblocks_short_4H": ['ranging_highvol'],
    "39_orderblocks_long_6Hutc": ['neutral'],  # excluded from calibration
    "40_orderblocks_short_6Hutc": ['neutral'],
}
