"""
regime_bins_E1.py — auto-generated regime classification. Do not edit manually.
Generated by main_regime.py (WFO mode) on 1Dutc
Auto-generated on 2026-07-03 10:54 UTC.
"""

INDICATOR_CFG = {'ma_window': 12}

OPTIMIZE_METRIC = "Calmar"

REGIME_BINS = {
    "01_reversal_long_15m": ['uptrend'],
    "02_reversal_short_15m": ['uptrend'],
    "03_reversal_long_30m": ['dwtrend'],
    "04_reversal_short_30m": ['dwtrend'],
    "05_reversal_long_1H": ['dwtrend'],
    "06_reversal_short_1H": [],
    "07_reversal_long_4H": [],
    "08_reversal_short_4H": ['dwtrend'],
    "09_reversal_long_6Hutc": ['uptrend'],
    "10_reversal_short_6Hutc": ['dwtrend'],
    "11_parity_long_15m": ['dwtrend'],
    "12_parity_short_15m": ['dwtrend'],
    "13_parity_long_30m": ['uptrend'],
    "14_parity_short_30m": ['dwtrend'],
    "15_parity_long_1H": [],
    "16_parity_short_1H": [],
    "17_parity_long_4H": ['uptrend'],
    "18_parity_short_4H": [],
    "19_parity_long_6Hutc": ['uptrend'],
    "20_parity_short_6Hutc": ['uptrend'],
    "21_flag_long_15m": ['uptrend'],
    "22_flag_short_15m": ['uptrend'],
    "23_flag_long_30m": ['uptrend'],
    "24_flag_short_30m": ['dwtrend'],
    "25_flag_long_1H": ['uptrend'],
    "26_flag_short_1H": ['uptrend'],
    "27_flag_long_4H": [],
    "28_flag_short_4H": ['dwtrend'],
    "29_flag_long_6Hutc": ['uptrend'],
    "30_flag_short_6Hutc": ['uptrend'],
    "31_orderblocks_long_15m": ['uptrend'],
    "32_orderblocks_short_15m": ['uptrend'],
    "33_orderblocks_long_30m": ['uptrend'],
    "34_orderblocks_short_30m": ['uptrend'],
    "35_orderblocks_long_1H": ['uptrend'],
    "36_orderblocks_short_1H": ['dwtrend'],
    "37_orderblocks_long_4H": ['dwtrend'],
    "38_orderblocks_short_4H": ['dwtrend'],
    "39_orderblocks_long_6Hutc": ['dwtrend'],
    "40_orderblocks_short_6Hutc": ['dwtrend'],
}
