"""
regime_bins_E1.py — MA uptrend regime classification. Do not edit manually.
Generated by regime_GE_calibration_uptrend.py — MA(3) on 1Dutc
Auto-generated on 2026-06-08 18:46 UTC.
"""

MA_WINDOW             = 3
MA_TIMEFRAME          = "1Dutc"
ANALYSIS_MODE         = "SYMBOL"

OPTIMIZE_METRIC = "calmar"

REGIME_BINS = {
    "01_reversal_long_15m": "uptrend",
    "02_reversal_short_15m": "downtrend",
    "03_reversal_long_30m": "uptrend",
    "04_reversal_short_30m": "downtrend",
    "05_reversal_long_1H": "uptrend",
    "06_reversal_short_1H": "downtrend",
    "07_reversal_long_4H": "uptrend",
    "08_reversal_short_4H": "downtrend",
    "09_reversal_long_6Hutc": "neutral",  # excluded from calibration
    "10_reversal_short_6Hutc": "downtrend",
    "11_parity_long_15m": "neutral",  # excluded from calibration
    "12_parity_short_15m": "downtrend",
    "13_parity_long_30m": "neutral",  # excluded from calibration
    "14_parity_short_30m": "neutral",
    "15_parity_long_1H": "uptrend",
    "16_parity_short_1H": "downtrend",
    "17_parity_long_4H": "uptrend",
    "18_parity_short_4H": "downtrend",
    "19_parity_long_6Hutc": "uptrend",
    "20_parity_short_6Hutc": "neutral",
    "21_flag_long_15m": "uptrend",
    "22_flag_short_15m": "downtrend",
    "23_flag_long_30m": "uptrend",
    "24_flag_short_30m": "neutral",
    "25_flag_long_1H": "uptrend",
    "26_flag_short_1H": "downtrend",
    "27_flag_long_4H": "uptrend",
    "28_flag_short_4H": "downtrend",
    "29_flag_long_6Hutc": "uptrend",
    "30_flag_short_6Hutc": "neutral",  # excluded from calibration
    "31_orderblocks_long_15m": "neutral",
    "32_orderblocks_short_15m": "downtrend",
    "33_orderblocks_long_30m": "neutral",
    "34_orderblocks_short_30m": "downtrend",
    "35_orderblocks_long_1H": "uptrend",
    "36_orderblocks_short_1H": "downtrend",
    "37_orderblocks_long_4H": "uptrend",
    "38_orderblocks_short_4H": "downtrend",
    "39_orderblocks_long_6Hutc": "neutral",  # excluded from calibration
    "40_orderblocks_short_6Hutc": "downtrend",
}
