"""
regime_bins_E1.py — auto-generated regime classification. Do not edit manually.
Generated by main_regime.py (WFO mode) on 1Dutc
Auto-generated on 2026-07-02 15:24 UTC.
"""

INDICATOR_CFG = {'ma_window': 10}

OPTIMIZE_METRIC = "Net_Gain_pct"

REGIME_BINS = {
    "05_reversal_long_1H": ['uptrend'],
    "06_reversal_short_1H": [],
    "07_reversal_long_4H": [],
    "08_reversal_short_4H": ['dwtrend'],
    "09_reversal_long_6Hutc": ['uptrend'],
    "10_reversal_short_6Hutc": ['dwtrend'],
    "15_parity_long_1H": ['dwtrend'],
    "16_parity_short_1H": [],
    "17_parity_long_4H": ['uptrend'],
    "18_parity_short_4H": [],
    "19_parity_long_6Hutc": ['uptrend'],
    "20_parity_short_6Hutc": ['uptrend'],
    "25_flag_long_1H": ['uptrend'],
    "26_flag_short_1H": ['uptrend'],
    "27_flag_long_4H": [],
    "28_flag_short_4H": ['dwtrend'],
    "29_flag_long_6Hutc": ['uptrend'],
    "30_flag_short_6Hutc": ['dwtrend'],
    "35_orderblocks_long_1H": ['uptrend'],
    "36_orderblocks_short_1H": ['dwtrend'],
    "37_orderblocks_long_4H": [],
    "38_orderblocks_short_4H": ['dwtrend'],
    "39_orderblocks_long_6Hutc": ['uptrend'],
    "40_orderblocks_short_6Hutc": [],
}
