"""
strategies_loop_00_01_rwa.py — Batch loop configuration for RWA.
Edit param_grid, N_SYMBOLS and ORDER_AMOUNT before each run.
This file is NOT updated by the batch automatically.
"""
N_SYMBOLS    = 10
ORDER_AMOUNT = 100

STRATEGIES_LOOP = [
    # =========================================================================
    # REVERSAL
    # =========================================================================
    {
        "id": "01_reversal_long_15m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [10],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "02_reversal_short_15m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [10],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "03_reversal_long_30m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [10],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "04_reversal_short_30m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [10],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "05_reversal_long_1H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [10],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "06_reversal_short_1H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [10],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "07_reversal_long_4H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [10],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "08_reversal_short_4H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [10],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "09_reversal_long_6Hutc",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [10],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "10_reversal_short_6Hutc",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [10],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    # =========================================================================
    # PARITY
    # =========================================================================
    {
        "id": "11_parity_long_15m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "12_parity_short_15m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "13_parity_long_30m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "14_parity_short_30m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "15_parity_long_1H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "16_parity_short_1H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "17_parity_long_4H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "18_parity_short_4H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "19_parity_long_6Hutc",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "20_parity_short_6Hutc",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [10,30],
            "MA_PERIOD": [10],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    # =========================================================================
    # FLAG
    # =========================================================================
    {
        "id": "21_flag_long_15m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [60],
            "MA_PERIOD": [10],
            "IMPULSE": [2, 4],
            "FLAG": [10,30],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "22_flag_short_15m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [60],
            "MA_PERIOD": [10],
            "IMPULSE": [2, 4],
            "FLAG": [10,30],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "23_flag_long_30m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [60],
            "MA_PERIOD": [10],
            "IMPULSE": [2, 4],
            "FLAG": [10,30],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "24_flag_short_30m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [60],
            "MA_PERIOD": [10],
            "IMPULSE": [2, 4],
            "FLAG": [10,30],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "25_flag_long_1H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [60],
            "MA_PERIOD": [10],
            "IMPULSE": [2, 4],
            "FLAG": [10,30],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "26_flag_short_1H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [60],
            "MA_PERIOD": [10],
            "IMPULSE": [2, 4],
            "FLAG": [10,30],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "27_flag_long_4H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [60],
            "MA_PERIOD": [10],
            "IMPULSE": [2, 4],
            "FLAG": [10,30],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "28_flag_short_4H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [60],
            "MA_PERIOD": [10],
            "IMPULSE": [2, 4],
            "FLAG": [10,30],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "29_flag_long_6Hutc",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [60],
            "MA_PERIOD": [10],
            "IMPULSE": [2, 4],
            "FLAG": [10,30],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "30_flag_short_6Hutc",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [60],
            "MA_PERIOD": [10],
            "IMPULSE": [2, 4],
            "FLAG": [10,30],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    # =========================================================================
    # ORDERBLOCKS
    # =========================================================================
    {
        "id": "31_orderblocks_long_15m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [30,40],
            "IMPULSE": [0.02,0.08],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "32_orderblocks_short_15m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [30,40],
            "IMPULSE": [0.02,0.08],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "33_orderblocks_long_30m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [30,40],
            "IMPULSE": [0.02,0.08],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "34_orderblocks_short_30m",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [30,40],
            "IMPULSE": [0.02,0.08],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "35_orderblocks_long_1H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [30,40],
            "IMPULSE": [0.02,0.08],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "36_orderblocks_short_1H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [30,40],
            "IMPULSE": [0.02,0.08],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "37_orderblocks_long_4H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [30,40],
            "IMPULSE": [0.02,0.08],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "38_orderblocks_short_4H",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [30,40],
            "IMPULSE": [0.02,0.08],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "39_orderblocks_long_6Hutc",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [30,40],
            "IMPULSE": [0.02,0.08],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
    {
        "id": "40_orderblocks_short_6Hutc",
        "N_SYMBOLS": N_SYMBOLS,
        "ORDER_AMOUNT": ORDER_AMOUNT,
        "param_grid": {
            "SELL_AFTER": [0],
            "LOOKBACK": [50],
            "TOLERANCE": [30,40],
            "IMPULSE": [0.02,0.08],
            "TP_PCT": [2,4,6,8,10],
            "SL_PCT": [2,4,6,8,10],
        },
    },
]