"""
strategies_BT_E1_batch.py — Input for BOT_batch. Do not edit manually.
Generated from strategies_E1.py. Re-run this script after each production deploy.
"""

STRATEGIES = [
    {
        "id": "07_reversal_short_1H",
        "name": "reversal_short_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 360,
        "lookback": 4,
        "tolerance": 15,
        "ma_period": 10,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "10_parity_long_1H",
        "name": "parity_long_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 360,
        "lookback": 150,
        "tolerance": 10,
        "ma_period": 10,
        "tp_pct": 3,
        "sl_pct": 3,
    },
    {
        "id": "11_parity_short_1H",
        "name": "parity_short_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 360,
        "lookback": 100,
        "tolerance": 10,
        "ma_period": 10,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "18_flag_long_1H",
        "name": "flag_long_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 360,
        "lookback": 40,
        "ma_period": 10,
        "impulse": 2,
        "flag": 30,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "20_flag_short_1H",
        "name": "flag_short_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 360,
        "lookback": 20,
        "ma_period": 10,
        "impulse": 2,
        "flag": 10,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "27_orderblocks_short_1H",
        "name": "orderblocks_short_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 360,
        "lookback": 75,
        "tolerance": 45,
        "impulse": 0.05,
        "tp_pct": 2,
        "sl_pct": 3,
    },
]
