"""
Regime OOS1 reference values for drift detection.
P_TARGET_WINRATE: Observed winrate on regime-filtered OOS1 trades (used as binomial p_target)
Auto-generated by BOT_batch on 2026-06-08 23:36. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '01_reversal_long_15m': {
        'p_target_winrate': 63.0,
    },
    '02_reversal_short_15m': {
        'p_target_winrate': 62.9,
    },
    '03_reversal_long_30m': {
        'p_target_winrate': 70.7,
    },
    '04_reversal_short_30m': {
        'p_target_winrate': 75.5,
    },
    '05_reversal_long_1H': {
        'p_target_winrate': 78.9,
    },
    '06_reversal_short_1H': {
        'p_target_winrate': 84.5,
    },
    '07_reversal_long_4H': {
        'p_target_winrate': 80.2,
    },
    '08_reversal_short_4H': {
        'p_target_winrate': 83.9,
    },
    '09_reversal_long_6Hutc': {
        'p_target_winrate': 75.6,
    },
    '10_reversal_short_6Hutc': {
        'p_target_winrate': 82.7,
    },
    '11_parity_long_15m': {
        'p_target_winrate': 57.4,
    },
    '12_parity_short_15m': {
        'p_target_winrate': 66.0,
    },
    '13_parity_long_30m': {
        'p_target_winrate': 67.2,
    },
    '14_parity_short_30m': {
        'p_target_winrate': 72.7,
    },
    '15_parity_long_1H': {
        'p_target_winrate': 79.8,
    },
    '16_parity_short_1H': {
        'p_target_winrate': 84.3,
    },
    '17_parity_long_4H': {
        'p_target_winrate': 82.5,
    },
    '18_parity_short_4H': {
        'p_target_winrate': 83.2,
    },
    '19_parity_long_6Hutc': {
        'p_target_winrate': 84.4,
    },
    '20_parity_short_6Hutc': {
        'p_target_winrate': 81.6,
    },
    '21_flag_long_15m': {
        'p_target_winrate': 68.6,
    },
    '22_flag_short_15m': {
        'p_target_winrate': 70.7,
    },
    '23_flag_long_30m': {
        'p_target_winrate': 73.2,
    },
    '24_flag_short_30m': {
        'p_target_winrate': 76.7,
    },
    '25_flag_long_1H': {
        'p_target_winrate': 81.0,
    },
    '26_flag_short_1H': {
        'p_target_winrate': 84.4,
    },
    '27_flag_long_4H': {
        'p_target_winrate': 80.9,
    },
    '28_flag_short_4H': {
        'p_target_winrate': 82.7,
    },
    '29_flag_long_6Hutc': {
        'p_target_winrate': 81.3,
    },
    '30_flag_short_6Hutc': {
        'p_target_winrate': 82.7,
    },
    '31_orderblocks_long_15m': {
        'p_target_winrate': 64.8,
    },
    '32_orderblocks_short_15m': {
        'p_target_winrate': 67.2,
    },
    '33_orderblocks_long_30m': {
        'p_target_winrate': 69.7,
    },
    '34_orderblocks_short_30m': {
        'p_target_winrate': 76.5,
    },
    '35_orderblocks_long_1H': {
        'p_target_winrate': 71.9,
    },
    '36_orderblocks_short_1H': {
        'p_target_winrate': 85.1,
    },
    '37_orderblocks_long_4H': {
        'p_target_winrate': 81.3,
    },
    '38_orderblocks_short_4H': {
        'p_target_winrate': 78.7,
    },
    '39_orderblocks_long_6Hutc': {
        'p_target_winrate': 78.3,
    },
    '40_orderblocks_short_6Hutc': {
        'p_target_winrate': 86.0,
    },
}
