"""
Regime OOS1 reference values for drift detection.
P_TARGET_WINRATE: Observed winrate on regime-filtered OOS1 trades (used as binomial p_target)
Auto-generated by BOT_batch on 2026-05-20 14:04. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '30_reversal_long_30m': {
        'p_target_winrate': 72.2,
    },
    '31_reversal_long_15m': {
        'p_target_winrate': 65.6,
    },
    '32_reversal_short_30m': {
        'p_target_winrate': 76.9,
    },
    '33_reversal_short_15m': {
        'p_target_winrate': 70.9,
    },
    '34_parity_long_30m': {
        'p_target_winrate': 71.7,
    },
    '35_parity_long_15m': {
        'p_target_winrate': 67.1,
    },
    '36_parity_short_30m': {
        'p_target_winrate': 77.1,
    },
    '37_parity_short_15m': {
        'p_target_winrate': 70.6,
    },
    '38_flag_long_30m': {
        'p_target_winrate': 72.9,
    },
    '39_flag_long_15m': {
        'p_target_winrate': 67.9,
    },
    '40_flag_short_30m': {
        'p_target_winrate': 78.6,
    },
    '41_flag_short_15m': {
        'p_target_winrate': 70.8,
    },
    '42_orderblocks_long_30m': {
        'p_target_winrate': 68.9,
    },
    '43_orderblocks_long_15m': {
        'p_target_winrate': 63.5,
    },
    '44_orderblocks_short_30m': {
        'p_target_winrate': 74.7,
    },
    '45_orderblocks_short_15m': {
        'p_target_winrate': 69.2,
    },
}
