"""
Regime OOS1 reference values for drift detection.
P_TARGET_WINRATE: Observed winrate on regime-filtered OOS1 trades (used as binomial p_target)
Auto-generated by BOT_batch on 2026-05-27 11:41. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '01_reversal_long_15m': {
        'p_target_winrate': 59.2,
    },
    '02_reversal_short_15m': {
        'p_target_winrate': 64.3,
    },
    '03_reversal_long_30m': {
        'p_target_winrate': 70.1,
    },
    '04_reversal_short_30m': {
        'p_target_winrate': 74.7,
    },
    '05_reversal_long_1H': {
        'p_target_winrate': 76.7,
    },
    '06_reversal_short_1H': {
        'p_target_winrate': 81.8,
    },
    '07_reversal_long_4H': {
        'p_target_winrate': 78.0,
    },
    '08_reversal_short_4H': {
        'p_target_winrate': 81.5,
    },
    '09_reversal_long_6Hutc': {
        'p_target_winrate': 75.6,
    },
    '10_reversal_short_6Hutc': {
        'p_target_winrate': 80.9,
    },
    '11_parity_long_15m': {
        'p_target_winrate': 57.4,
    },
    '12_parity_short_15m': {
        'p_target_winrate': 65.5,
    },
    '13_parity_long_30m': {
        'p_target_winrate': 67.2,
    },
    '14_parity_short_30m': {
        'p_target_winrate': 75.2,
    },
    '15_parity_long_1H': {
        'p_target_winrate': 77.9,
    },
    '16_parity_short_1H': {
        'p_target_winrate': 81.5,
    },
    '17_parity_long_4H': {
        'p_target_winrate': 79.5,
    },
    '18_parity_short_4H': {
        'p_target_winrate': 80.7,
    },
    '19_parity_long_6Hutc': {
        'p_target_winrate': 82.2,
    },
    '20_parity_short_6Hutc': {
        'p_target_winrate': 80.3,
    },
    '21_flag_long_15m': {
        'p_target_winrate': 64.7,
    },
    '22_flag_short_15m': {
        'p_target_winrate': 70.2,
    },
    '23_flag_long_30m': {
        'p_target_winrate': 68.7,
    },
    '24_flag_short_30m': {
        'p_target_winrate': 76.7,
    },
    '25_flag_long_1H': {
        'p_target_winrate': 78.3,
    },
    '26_flag_short_1H': {
        'p_target_winrate': 81.4,
    },
    '27_flag_long_4H': {
        'p_target_winrate': 78.5,
    },
    '28_flag_short_4H': {
        'p_target_winrate': 81.0,
    },
    '29_flag_long_6Hutc': {
        'p_target_winrate': 79.9,
    },
    '30_flag_short_6Hutc': {
        'p_target_winrate': 82.7,
    },
    '31_orderblocks_long_15m': {
        'p_target_winrate': 64.8,
    },
    '32_orderblocks_short_15m': {
        'p_target_winrate': 67.6,
    },
    '33_orderblocks_long_30m': {
        'p_target_winrate': 69.7,
    },
    '34_orderblocks_short_30m': {
        'p_target_winrate': 74.6,
    },
    '35_orderblocks_long_1H': {
        'p_target_winrate': 70.4,
    },
    '36_orderblocks_short_1H': {
        'p_target_winrate': 83.7,
    },
    '37_orderblocks_long_4H': {
        'p_target_winrate': 77.1,
    },
    '38_orderblocks_short_4H': {
        'p_target_winrate': 76.2,
    },
    '39_orderblocks_long_6Hutc': {
        'p_target_winrate': 78.3,
    },
    '40_orderblocks_short_6Hutc': {
        'p_target_winrate': 84.0,
    },
}
