"""
Trading Strategies Configuration

Auto-generated by BOT_batch. Do not edit manually.
Copy to BOT_trading/config/strategies_NN.py to deploy.
"""

STRATEGIES = [
    {
        "id": "07_reversal_short_1H",
        "name": "reversal_short_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0,
        "regime_trending_dwtrend": 1,
        "regime_ranging_uptrend": 0,
        "regime_ranging_dwtrend": 1,
        "regime_volatile_uptrend": 0,
        "regime_volatile_dwtrend": 1,
        "sell_after_ncandles": 100,
        "order_amount": 240,
        "ma_period": 10,
        "tolerance": 15,
        "lookback": 4,
        "tp_pct": 2,
        "sl_pct": 3,
    },
    {
        "id": "10_parity_long_1H",
        "name": "parity_long_1H",
        "timeframe": "1H",
        "active": True,
        "direction": "long",
        "regime_trending_uptrend": 1,
        "regime_trending_dwtrend": 0,
        "regime_ranging_uptrend": 1,
        "regime_ranging_dwtrend": 0,
        "regime_volatile_uptrend": 1,
        "regime_volatile_dwtrend": 0,
        "sell_after_ncandles": 75,
        "order_amount": 240,
        "ma_period": 10,
        "tolerance": 10,
        "lookback": 150,
        "tp_pct": 2,
        "sl_pct": 3,
    },
]
