"""
strategies_BT_00_batch.py — Input for BOT_batch. Do not edit manually.
Generated from strategies_00.py. Re-run this script after each production deploy.
"""

STRATEGIES = [
    {
        "id": "30_reversal_long_1H",
        "name": "reversal_long_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 80,
        "lookback": 10,
        "tolerance": 10,
        "ma_period": 25,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "31_reversal_long_30m",
        "name": "reversal_long_30m",
        "timeframe": "30m",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 80,
        "lookback": 10,
        "tolerance": 10,
        "ma_period": 25,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "32_reversal_long_15m",
        "name": "reversal_long_15m",
        "timeframe": "15m",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 80,
        "lookback": 10,
        "tolerance": 10,
        "ma_period": 25,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "33_reversal_short_1H",
        "name": "reversal_short_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 80,
        "lookback": 8,
        "tolerance": 30,
        "ma_period": 25,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "34_reversal_short_30m",
        "name": "reversal_short_30m",
        "timeframe": "30m",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 80,
        "lookback": 8,
        "tolerance": 10,
        "ma_period": 25,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "36_parity_long_1H",
        "name": "parity_long_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 80,
        "lookback": 50,
        "tolerance": 10,
        "ma_period": 25,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "37_parity_long_30m",
        "name": "parity_long_30m",
        "timeframe": "30m",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 80,
        "lookback": 50,
        "tolerance": 10,
        "ma_period": 25,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "38_parity_long_15m",
        "name": "parity_long_15m",
        "timeframe": "15m",
        "active": True,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 80,
        "lookback": 50,
        "tolerance": 10,
        "ma_period": 25,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "39_parity_short_1H",
        "name": "parity_short_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 80,
        "lookback": 100,
        "tolerance": 10,
        "ma_period": 25,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "40_parity_short_30m",
        "name": "parity_short_30m",
        "timeframe": "30m",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 200,
        "lookback": 50,
        "tolerance": 10,
        "ma_period": 25,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "41_parity_short_15m",
        "name": "parity_short_15m",
        "timeframe": "15m",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 80,
        "lookback": 50,
        "tolerance": 10,
        "ma_period": 25,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "42_flag_long_1H",
        "name": "flag_long_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 80,
        "lookback": 20,
        "ma_period": 50,
        "impulse": 6,
        "flag": 20,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "43_flag_long_30m",
        "name": "flag_long_30m",
        "timeframe": "30m",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 80,
        "lookback": 20,
        "ma_period": 50,
        "impulse": 6,
        "flag": 40,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "44_flag_long_15m",
        "name": "flag_long_15m",
        "timeframe": "15m",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 50,
        "order_amount_prod": 80,
        "lookback": 20,
        "ma_period": 50,
        "impulse": 6,
        "flag": 60,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "45_flag_short_1H",
        "name": "flag_short_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 80,
        "lookback": 60,
        "ma_period": 25,
        "impulse": 6,
        "flag": 40,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "46_flag_short_30m",
        "name": "flag_short_30m",
        "timeframe": "30m",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 80,
        "lookback": 60,
        "ma_period": 25,
        "impulse": 4,
        "flag": 20,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "47_flag_short_15m",
        "name": "flag_short_15m",
        "timeframe": "15m",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 100,
        "order_amount_prod": 80,
        "lookback": 20,
        "ma_period": 50,
        "impulse": 6,
        "flag": 40,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "48_orderblocks_long_1H",
        "name": "orderblocks_long_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 80,
        "lookback": 30,
        "tolerance": 25,
        "impulse": 0.08,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "49_orderblocks_long_30m",
        "name": "orderblocks_long_30m",
        "timeframe": "30m",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 80,
        "lookback": 30,
        "tolerance": 25,
        "impulse": 0.08,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "50_orderblocks_long_15m",
        "name": "orderblocks_long_15m",
        "timeframe": "15m",
        "active": False,
        "direction": "long",
        "regime_trending_uptrend": 1.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 1.0,
        "regime_ranging_dwtrend": 0.0,
        "regime_volatile_uptrend": 1.0,
        "regime_volatile_dwtrend": 0.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 80,
        "lookback": 30,
        "tolerance": 20,
        "impulse": 0.08,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "51_orderblocks_short_1H",
        "name": "orderblocks_short_1H",
        "timeframe": "1H",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 80,
        "lookback": 30,
        "tolerance": 20,
        "impulse": 0.08,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "52_orderblocks_short_30m",
        "name": "orderblocks_short_30m",
        "timeframe": "30m",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 0.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 80,
        "lookback": 30,
        "tolerance": 20,
        "impulse": 0.02,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "53_orderblocks_short_15m",
        "name": "orderblocks_short_15m",
        "timeframe": "15m",
        "active": False,
        "direction": "short",
        "regime_trending_uptrend": 0.0,
        "regime_trending_dwtrend": 1.0,
        "regime_ranging_uptrend": 0.0,
        "regime_ranging_dwtrend": 1.0,
        "regime_volatile_uptrend": 0.0,
        "regime_volatile_dwtrend": 1.0,
        "sell_after_ncandles": 75,
        "order_amount_prod": 80,
        "lookback": 30,
        "tolerance": 20,
        "impulse": 0.08,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
]
