"""
Regime OOS1 reference values for drift detection.
P_TARGET_WINRATE: Observed winrate on regime-filtered OOS1 trades (used as binomial p_target)
Auto-generated by BOT_batch on 2026-05-17 02:48. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '30_reversal_long_1H': {
        'p_target_winrate': 67.5,
    },
    '31_reversal_long_30m': {
        'p_target_winrate': 69.3,
    },
    '32_reversal_long_15m': {
        'p_target_winrate': 64.1,
    },
    '33_reversal_short_1H': {
        'p_target_winrate': 78.5,
    },
    '34_reversal_short_30m': {
        'p_target_winrate': 73.9,
    },
    '35_reversal_short_15m': {
        'p_target_winrate': 69.0,
    },
    '36_parity_long_1H': {
        'p_target_winrate': 73.6,
    },
    '37_parity_long_30m': {
        'p_target_winrate': 70.2,
    },
    '38_parity_long_15m': {
        'p_target_winrate': 66.6,
    },
    '39_parity_short_1H': {
        'p_target_winrate': 78.5,
    },
    '40_parity_short_30m': {
        'p_target_winrate': 73.5,
    },
    '41_parity_short_15m': {
        'p_target_winrate': 68.4,
    },
    '42_flag_long_1H': {
        'p_target_winrate': 73.2,
    },
    '43_flag_long_30m': {
        'p_target_winrate': 73.9,
    },
    '44_flag_long_15m': {
        'p_target_winrate': 67.2,
    },
    '45_flag_short_1H': {
        'p_target_winrate': 78.6,
    },
    '46_flag_short_30m': {
        'p_target_winrate': 76.3,
    },
    '47_flag_short_15m': {
        'p_target_winrate': 69.3,
    },
    '48_orderblocks_long_1H': {
        'p_target_winrate': 62.7,
    },
    '49_orderblocks_long_30m': {
        'p_target_winrate': 69.0,
    },
    '50_orderblocks_long_15m': {
        'p_target_winrate': 63.5,
    },
    '51_orderblocks_short_1H': {
        'p_target_winrate': 75.6,
    },
    '52_orderblocks_short_30m': {
        'p_target_winrate': 74.1,
    },
    '53_orderblocks_short_15m': {
        'p_target_winrate': 67.5,
    },
}
