"""
Regime OOS1 reference values for drift detection.
P_TARGET_WINRATE: Observed winrate on regime-filtered OOS1 trades (used as binomial p_target)
Auto-generated by BOT_batch on 2026-06-09 21:03. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '01_reversal_long_15m': {
        'p_target_winrate': 60.7,
    },
    '02_reversal_short_15m': {
        'p_target_winrate': 62.7,
    },
    '03_reversal_long_30m': {
        'p_target_winrate': 65.0,
    },
    '04_reversal_short_30m': {
        'p_target_winrate': 67.3,
    },
    '05_reversal_long_1H': {
        'p_target_winrate': 60.1,
    },
    '06_reversal_short_1H': {
        'p_target_winrate': 73.3,
    },
    '07_reversal_long_4H': {
        'p_target_winrate': 55.1,
    },
    '08_reversal_short_4H': {
        'p_target_winrate': 57.1,
    },
    '09_reversal_long_6Hutc': {
        'p_target_winrate': 58.4,
    },
    '10_reversal_short_6Hutc': {
        'p_target_winrate': 59.8,
    },
    '11_parity_long_15m': {
        'p_target_winrate': 61.8,
    },
    '12_parity_short_15m': {
        'p_target_winrate': 62.4,
    },
    '13_parity_long_30m': {
        'p_target_winrate': 64.6,
    },
    '14_parity_short_30m': {
        'p_target_winrate': 67.2,
    },
    '15_parity_long_1H': {
        'p_target_winrate': 70.1,
    },
    '16_parity_short_1H': {
        'p_target_winrate': 75.5,
    },
    '17_parity_long_4H': {
        'p_target_winrate': 61.9,
    },
    '18_parity_short_4H': {
        'p_target_winrate': 56.0,
    },
    '19_parity_long_6Hutc': {
        'p_target_winrate': 54.5,
    },
    '20_parity_short_6Hutc': {
        'p_target_winrate': 62.5,
    },
    '21_flag_long_15m': {
        'p_target_winrate': 64.8,
    },
    '22_flag_short_15m': {
        'p_target_winrate': 65.6,
    },
    '23_flag_long_30m': {
        'p_target_winrate': 68.9,
    },
    '24_flag_short_30m': {
        'p_target_winrate': 71.1,
    },
    '25_flag_long_1H': {
        'p_target_winrate': 69.8,
    },
    '26_flag_short_1H': {
        'p_target_winrate': 74.5,
    },
    '27_flag_long_4H': {
        'p_target_winrate': 49.4,
    },
    '28_flag_short_4H': {
        'p_target_winrate': 66.9,
    },
    '29_flag_long_6Hutc': {
        'p_target_winrate': 52.8,
    },
    '30_flag_short_6Hutc': {
        'p_target_winrate': 68.2,
    },
    '31_orderblocks_long_15m': {
        'p_target_winrate': 60.7,
    },
    '32_orderblocks_short_15m': {
        'p_target_winrate': 62.8,
    },
    '33_orderblocks_long_30m': {
        'p_target_winrate': 64.2,
    },
    '34_orderblocks_short_30m': {
        'p_target_winrate': 66.9,
    },
    '35_orderblocks_long_1H': {
        'p_target_winrate': 58.3,
    },
    '36_orderblocks_short_1H': {
        'p_target_winrate': 70.5,
    },
    '37_orderblocks_long_4H': {
        'p_target_winrate': 50.9,
    },
    '38_orderblocks_short_4H': {
        'p_target_winrate': 56.7,
    },
    '39_orderblocks_long_6Hutc': {
        'p_target_winrate': 47.7,
    },
    '40_orderblocks_short_6Hutc': {
        'p_target_winrate': 58.2,
    },
}
