"""
Regime OOS1 reference values for drift detection.
P_TARGET_WINRATE: Observed winrate on regime-filtered OOS1 trades (used as binomial p_target)
Auto-generated by BOT_batch on 2026-06-09 13:28. Do not edit manually.
"""
DRIFT_REFERENCE = {
    '01_reversal_long_15m': {
        'p_target_winrate': 60.0,
    },
    '02_reversal_short_15m': {
        'p_target_winrate': 63.1,
    },
    '03_reversal_long_30m': {
        'p_target_winrate': 62.1,
    },
    '04_reversal_short_30m': {
        'p_target_winrate': 68.1,
    },
    '05_reversal_long_1H': {
        'p_target_winrate': 59.7,
    },
    '06_reversal_short_1H': {
        'p_target_winrate': 74.5,
    },
    '07_reversal_long_4H': {
        'p_target_winrate': 54.3,
    },
    '08_reversal_short_4H': {
        'p_target_winrate': 57.9,
    },
    '09_reversal_long_6Hutc': {
        'p_target_winrate': 56.9,
    },
    '10_reversal_short_6Hutc': {
        'p_target_winrate': 62.1,
    },
    '11_parity_long_15m': {
        'p_target_winrate': 59.8,
    },
    '12_parity_short_15m': {
        'p_target_winrate': 63.0,
    },
    '13_parity_long_30m': {
        'p_target_winrate': 62.7,
    },
    '14_parity_short_30m': {
        'p_target_winrate': 68.2,
    },
    '15_parity_long_1H': {
        'p_target_winrate': 69.4,
    },
    '16_parity_short_1H': {
        'p_target_winrate': 75.4,
    },
    '17_parity_long_4H': {
        'p_target_winrate': 61.6,
    },
    '18_parity_short_4H': {
        'p_target_winrate': 57.6,
    },
    '19_parity_long_6Hutc': {
        'p_target_winrate': 52.8,
    },
    '20_parity_short_6Hutc': {
        'p_target_winrate': 64.5,
    },
    '21_flag_long_15m': {
        'p_target_winrate': 64.6,
    },
    '22_flag_short_15m': {
        'p_target_winrate': 66.3,
    },
    '23_flag_long_30m': {
        'p_target_winrate': 69.2,
    },
    '24_flag_short_30m': {
        'p_target_winrate': 70.8,
    },
    '25_flag_long_1H': {
        'p_target_winrate': 80.9,
    },
    '26_flag_short_1H': {
        'p_target_winrate': 75.4,
    },
    '27_flag_long_4H': {
        'p_target_winrate': 50.0,
    },
    '28_flag_short_4H': {
        'p_target_winrate': 66.4,
    },
    '29_flag_long_6Hutc': {
        'p_target_winrate': 54.1,
    },
    '30_flag_short_6Hutc': {
        'p_target_winrate': 68.1,
    },
    '31_orderblocks_long_15m': {
        'p_target_winrate': 61.7,
    },
    '32_orderblocks_short_15m': {
        'p_target_winrate': 60.8,
    },
    '33_orderblocks_long_30m': {
        'p_target_winrate': 63.8,
    },
    '34_orderblocks_short_30m': {
        'p_target_winrate': 68.1,
    },
    '35_orderblocks_long_1H': {
        'p_target_winrate': 57.2,
    },
    '36_orderblocks_short_1H': {
        'p_target_winrate': 70.9,
    },
    '37_orderblocks_long_4H': {
        'p_target_winrate': 55.4,
    },
    '38_orderblocks_short_4H': {
        'p_target_winrate': 60.3,
    },
    '39_orderblocks_long_6Hutc': {
        'p_target_winrate': 54.3,
    },
    '40_orderblocks_short_6Hutc': {
        'p_target_winrate': 61.8,
    },
}
