"""
Trading Strategies Configuration

Auto-generated by BOT_batch. Do not edit manually.
Copy to BOT_trading/config/strategies_NN.py to deploy.
"""

STRATEGIES = [
    {
        "id": "34_reversal_short_30m",
        "name": "reversal_short_30m",
        "timeframe": "30m",
        "active": True,
        "direction": "short",
        "regime_trending_uptrend": 0,
        "regime_trending_dwtrend": 0,
        "regime_ranging_uptrend": 0,
        "regime_ranging_dwtrend": 1,
        "regime_volatile_uptrend": 0,
        "regime_volatile_dwtrend": 1,
        "sell_after_ncandles": 100,
        "order_amount": 200,
        "ma_period": 25,
        "tolerance": 10,
        "lookback": 8,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
    {
        "id": "38_parity_long_15m",
        "name": "parity_long_15m",
        "timeframe": "15m",
        "active": True,
        "direction": "long",
        "regime_trending_uptrend": 1,
        "regime_trending_dwtrend": 0,
        "regime_ranging_uptrend": 1,
        "regime_ranging_dwtrend": 0,
        "regime_volatile_uptrend": 1,
        "regime_volatile_dwtrend": 0,
        "sell_after_ncandles": 75,
        "order_amount": 200,
        "ma_period": 25,
        "tolerance": 10,
        "lookback": 50,
        "tp_pct": 2.0,
        "sl_pct": 3.0,
    },
]
