#shared/shared_batchs/rule_mining/rule_deploy.py
import os
import logging
from datetime import datetime

import pandas as pd

from shared_batchs.pipeline.wfo import WFO_WINDOW_CONFIG
from shared_batchs.runs.run_deploy import (
    _slice_deploy_window,
    _select_deploy_symbols,
    _run_deploy_grid,
    _save_deploy_symbols,
)

logger = logging.getLogger("BOT_batch.rule_mining.deploy")


def _fmt_spec(spec: dict) -> str:
    return (
        f'{{"type": "{spec["type"]}", "op": "{spec["op"]}", "value": {spec["value"]}}}'
    )


def _build_window_summary_lines(deploy_map: dict) -> list:
    seen_tfs = {}
    lines    = []

    for entry in deploy_map.values():
        tf = entry.get("timeframe")
        if tf is None or tf in seen_tfs:
            continue
        seen_tfs[tf] = True

        ts = entry.get("train_start_ts")
        te = entry.get("train_end_ts")
        if ts is None or te is None:
            continue

        wfo_cfg     = WFO_WINDOW_CONFIG.get(tf, {})
        train_m     = wfo_cfg.get("train_months")
        test_m      = wfo_cfg.get("test_months")
        ts_str      = pd.Timestamp(ts).strftime("%Y-%m-%d")
        te_str      = pd.Timestamp(te).strftime("%Y-%m-%d")
        next_str    = (pd.Timestamp(te) + pd.DateOffset(months=int(test_m))).strftime("%Y-%m-%d") if test_m is not None else "?"
        train_m_str = f"{int(train_m)}m train" if train_m is not None else "?m train"
        test_m_str  = f"+{int(test_m)}m" if test_m is not None else "?"

        lines.append(f'  {tf:<12}: {ts_str} → {te_str}  ({train_m_str})  |  next train: {next_str}  ({test_m_str})')

    return lines


def _save_rule_deploy_batch(
    output_path: str,
    deploy_map: dict,
) -> None:

    lines = [
        '"""',
        'Rule Mining Strategies Configuration — Deploy',
        '',
        f'Auto-generated by run_deploy_rule on {datetime.now().strftime("%Y-%m-%d %H:%M")}. Do not edit manually.',
    ]

    window_lines = _build_window_summary_lines(deploy_map)
    if window_lines:
        lines += ['', 'Train windows:'] + window_lines

    lines += ['"""', '', 'RULES = [']

    sorted_ids = sorted(deploy_map.keys(), key=lambda rid: int(rid.split("_")[0]))

    for rule_id in sorted_ids:
        entry     = deploy_map[rule_id]
        specs_str = ", ".join(_fmt_spec(s) for s in entry["specs"])

        lines.append("    {")
        lines.append(f'        "id": "{rule_id}",')
        lines.append(f'        "timeframe": "{entry["timeframe"]}",')
        lines.append(f'        "active": {entry["approved"]},')
        lines.append(f'        "direction": "{entry["side"]}",')
        lines.append(f'        "specs": [{specs_str}],')
        lines.append(f'        "sell_after_ncandles": {entry["params"]["SELL_AFTER"]},')
        lines.append(f'        "order_amount": {entry["order_amount"]},')
        lines.append(f'        "tp_pct": {entry["params"]["TP_PCT"]},')
        lines.append(f'        "sl_pct": {entry["params"]["SL_PCT"]},')
        lines.append("    },")

    lines.append("]")

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    logger.info(f"DEPLOY ── rule mining batch saved → {output_path}")


def run_deploy_rule(
    rule_id: str,
    specs: list,
    side: str,
    ohlcv_is: dict,
    signal_fn: callable,
    param_grid: dict,
    order_amount: int,
    timeframe: str,
    n_symbols: int,
    approved: bool,
    dtype,
    n_jobs: int,
    symbols_live_folder: str,
    deploy_map: dict,
    label_width: int = 0,
) -> bool:

    label = f"{rule_id:<{label_width}}"

    logger.info(f"DEPLOY  ── {label} ── running deploy train window")

    param_names    = list(param_grid.keys())
    lists_for_grid = [param_grid[k] for k in param_names]

    ohlcv_window, train_start_ts, train_end_ts = _slice_deploy_window(ohlcv_is, timeframe)
    ohlcv_selected = _select_deploy_symbols(ohlcv_window, n_symbols, train_start_ts)
    deploy_symbols = list(ohlcv_selected.keys())
    logger.info(
        f"DEPLOY  ── {label} ── {len(deploy_symbols):>3} symbols | "
        f"from {pd.Timestamp(train_start_ts)} to {pd.Timestamp(train_end_ts)}"
    )

    deploy_params = _run_deploy_grid(
        ohlcv_selected     = ohlcv_selected,
        param_names        = param_names,
        lists_for_grid     = lists_for_grid,
        signal_fn          = signal_fn,
        signal_params_keys = [],
        order_amount       = order_amount,
        dtype              = dtype,
        n_jobs             = n_jobs,
    )

    params_str = " | ".join(f"{k}={v}" for k, v in deploy_params.items() if k != "SELL_AFTER")
    status     = "🟢 active" if approved else "🔴 inactive"
    logger.info(f"DEPLOY  ── {label} ── {status} | {params_str}")

    deploy_map[rule_id] = {
        "specs":          specs,
        "side":           side,
        "timeframe":      timeframe,
        "params":         deploy_params,
        "approved":       approved,
        "order_amount":   order_amount,
        "train_start_ts": train_start_ts,
        "train_end_ts":   train_end_ts,
    }

    symbols_changed = _save_deploy_symbols(rule_id, deploy_symbols, timeframe, symbols_live_folder)

    return symbols_changed